// Curated career seed data.
// Salaries and outlook are 2023 BLS Occupational Employment and Wage Statistics / Occupational Outlook Handbook.
// SOC codes map to O*NET (https://www.onetonline.org/link/summary/<soc>).
// To expand, see scripts/fetch-onet.ts for the ingestion path.

export type OutlookLabel = "much-faster" | "faster" | "average" | "slower" | "declining";

export interface Career {
  slug: string;
  title: string;
  soc: string;
  shortDescription: string;
  medianSalary: number;
  salaryP10: number;
  salaryP90: number;
  outlookPct: number;
  outlookLabel: OutlookLabel;
  educationRequired: string;
  relatedMajorSlugs: string[];
  dayInLife: string[];
  topTasks: string[];
  growthNote?: string;
}

export const OUTLOOK_LABELS: Record<OutlookLabel, { label: string; color: string }> = {
  "much-faster": { label: "Much faster than average", color: "bg-emerald-100 text-emerald-800 border-emerald-200" },
  faster: { label: "Faster than average", color: "bg-green-100 text-green-800 border-green-200" },
  average: { label: "Average growth", color: "bg-blue-100 text-blue-800 border-blue-200" },
  slower: { label: "Slower than average", color: "bg-amber-100 text-amber-800 border-amber-200" },
  declining: { label: "Declining", color: "bg-rose-100 text-rose-800 border-rose-200" },
};

export function outlookFromPct(pct: number): OutlookLabel {
  if (pct >= 15) return "much-faster";
  if (pct >= 8) return "faster";
  if (pct >= 3) return "average";
  if (pct >= 0) return "slower";
  return "declining";
}

export const CAREERS: Career[] = [
  {
    slug: "software-developer",
    title: "Software Developer",
    soc: "15-1252",
    shortDescription: "Design, build, and maintain software — from consumer apps to backend systems that run the internet.",
    medianSalary: 132270,
    salaryP10: 77020,
    salaryP90: 208620,
    outlookPct: 25,
    outlookLabel: "much-faster",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["computer-science", "data-science", "engineering"],
    dayInLife: [
      "Review pull requests from teammates over coffee",
      "Stand-up with your team to unblock each other",
      "Pair with a designer on a new feature prototype",
      "Write and test code, iterating on performance",
      "Deploy, monitor, and fix anything that breaks",
    ],
    topTasks: [
      "Modify existing software to correct errors or improve performance",
      "Analyze user needs and design software to meet them",
      "Consult with other developers, designers, and PMs",
      "Document the designs and processes of software",
    ],
    growthNote: "25% growth 2022–2032 — among the fastest-growing occupations in the US.",
  },
  {
    slug: "data-scientist",
    title: "Data Scientist",
    soc: "15-2051",
    shortDescription: "Turn data into decisions — using statistics, ML, and storytelling to answer business questions.",
    medianSalary: 108020,
    salaryP10: 61070,
    salaryP90: 184090,
    outlookPct: 35,
    outlookLabel: "much-faster",
    educationRequired: "Bachelor's or master's",
    relatedMajorSlugs: ["data-science", "computer-science", "finance"],
    dayInLife: [
      "Run exploratory analysis on a new dataset",
      "Build or tune a model and validate its accuracy",
      "Present findings to non-technical stakeholders",
      "Collaborate with engineers to deploy a model into production",
    ],
    topTasks: [
      "Apply data mining, cleansing, and statistical analysis",
      "Develop models to forecast or classify outcomes",
      "Create visualizations and dashboards",
    ],
  },
  {
    slug: "mechanical-engineer",
    title: "Mechanical Engineer",
    soc: "17-2141",
    shortDescription: "Design the physical systems in cars, aircraft, robots, HVAC, medical devices — anything that moves.",
    medianSalary: 99510,
    salaryP10: 63860,
    salaryP90: 157470,
    outlookPct: 10,
    outlookLabel: "faster",
    educationRequired: "Bachelor's degree (ABET-accredited)",
    relatedMajorSlugs: ["engineering"],
    dayInLife: [
      "Draft CAD models for a new component",
      "Run simulations to stress-test a design",
      "Meet with manufacturing to hand off specs",
      "Walk the shop floor to observe how parts fit together",
    ],
    topTasks: [
      "Design mechanical products, devices, and systems",
      "Analyze test results and modify designs",
      "Oversee manufacturing and installation",
    ],
  },
  {
    slug: "civil-engineer",
    title: "Civil Engineer",
    soc: "17-2051",
    shortDescription: "Design and oversee roads, bridges, water systems, and the structures that make cities work.",
    medianSalary: 95890,
    salaryP10: 63600,
    salaryP90: 144560,
    outlookPct: 5,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree + PE license",
    relatedMajorSlugs: ["engineering"],
    dayInLife: [
      "Review structural plans for a new building",
      "Site visit to inspect construction progress",
      "Coordinate with architects and contractors",
      "Analyze soil reports and drainage calculations",
    ],
    topTasks: [
      "Analyze survey reports, maps, and long-range plans",
      "Perform or oversee soil testing",
      "Manage the repair or replacement of infrastructure",
    ],
  },
  {
    slug: "registered-nurse",
    title: "Registered Nurse (RN)",
    soc: "29-1141",
    shortDescription: "Frontline patient care in hospitals, clinics, and specialty settings — the backbone of modern medicine.",
    medianSalary: 86070,
    salaryP10: 63720,
    salaryP90: 132680,
    outlookPct: 6,
    outlookLabel: "average",
    educationRequired: "Associate's or BSN + NCLEX-RN",
    relatedMajorSlugs: ["nursing", "biology"],
    dayInLife: [
      "Take report on your patients at the start of shift",
      "Administer medications, assess vitals, chart findings",
      "Coordinate with doctors, therapists, and family",
      "Respond to emergencies and support patients through them",
    ],
    topTasks: [
      "Assess patients' conditions",
      "Administer medicines and treatments",
      "Operate and monitor medical equipment",
      "Educate patients and their families on managing illness",
    ],
  },
  {
    slug: "nurse-practitioner",
    title: "Nurse Practitioner",
    soc: "29-1171",
    shortDescription: "Advanced-practice RN who diagnoses, prescribes, and often practices independently.",
    medianSalary: 126260,
    salaryP10: 94530,
    salaryP90: 168030,
    outlookPct: 45,
    outlookLabel: "much-faster",
    educationRequired: "Master's in nursing",
    relatedMajorSlugs: ["nursing"],
    dayInLife: [
      "See patients for full visits: diagnose, prescribe, follow up",
      "Order and interpret labs and imaging",
      "Consult with physicians on complex cases",
    ],
    topTasks: [
      "Examine patients and diagnose conditions",
      "Prescribe medications",
      "Order tests and analyze results",
    ],
    growthNote: "Fastest-growing occupation in healthcare.",
  },
  {
    slug: "physician",
    title: "Physician",
    soc: "29-1229",
    shortDescription: "Diagnose and treat disease. Long training path — med school + residency — but broad autonomy and pay.",
    medianSalary: 239200,
    salaryP10: 118000,
    salaryP90: 239200,
    outlookPct: 3,
    outlookLabel: "average",
    educationRequired: "MD or DO + residency",
    relatedMajorSlugs: ["biology"],
    dayInLife: [
      "Morning rounds on inpatients",
      "Clinic visits — diagnose, prescribe, refer",
      "Procedures, from minor to complex",
      "Chart notes, billing, and teaching residents",
    ],
    topTasks: [
      "Diagnose and treat injuries or illness",
      "Prescribe and administer treatment",
      "Order and interpret tests",
    ],
  },
  {
    slug: "financial-analyst",
    title: "Financial Analyst",
    soc: "13-2051",
    shortDescription: "Analyze companies, markets, and investments to guide business decisions or portfolio allocation.",
    medianSalary: 99890,
    salaryP10: 61630,
    salaryP90: 175720,
    outlookPct: 8,
    outlookLabel: "faster",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["finance", "business", "political-science"],
    dayInLife: [
      "Build financial models in Excel or Python",
      "Read earnings reports and 10-Ks",
      "Pitch a buy/sell thesis to the team",
      "Meet with company management on research calls",
    ],
    topTasks: [
      "Evaluate current and historical financial data",
      "Study economic and business trends",
      "Recommend individual investments",
    ],
  },
  {
    slug: "accountant",
    title: "Accountant / Auditor",
    soc: "13-2011",
    shortDescription: "Track, audit, and report on money — at companies, for governments, or for individuals.",
    medianSalary: 79880,
    salaryP10: 50440,
    salaryP90: 137280,
    outlookPct: 4,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree (CPA for advancement)",
    relatedMajorSlugs: ["finance", "business"],
    dayInLife: [
      "Reconcile the month-end books",
      "Prepare tax filings or audit workpapers",
      "Meet with clients or business units",
    ],
    topTasks: [
      "Examine financial statements for accuracy",
      "Compute taxes owed and prepare tax returns",
      "Inspect account books and accounting systems",
    ],
  },
  {
    slug: "management-consultant",
    title: "Management Consultant",
    soc: "13-1111",
    shortDescription: "Help organizations solve problems — strategy, operations, tech. Intense, well-paid, travel-heavy.",
    medianSalary: 99410,
    salaryP10: 58960,
    salaryP90: 175110,
    outlookPct: 10,
    outlookLabel: "faster",
    educationRequired: "Bachelor's (MBA common for promotion)",
    relatedMajorSlugs: ["business", "finance", "political-science"],
    dayInLife: [
      "Client workshop in the morning",
      "Interview stakeholders and collect data",
      "Build slides synthesising insights",
      "Present recommendations to executives",
    ],
    topTasks: [
      "Gather and organize information about the problem",
      "Interview personnel and observe operations",
      "Develop solutions and recommend new systems",
    ],
  },
  {
    slug: "marketing-manager",
    title: "Marketing Manager",
    soc: "11-2021",
    shortDescription: "Own how a product or brand is positioned — strategy, campaigns, budget, team.",
    medianSalary: 157620,
    salaryP10: 81680,
    salaryP90: 239200,
    outlookPct: 6,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["business", "communications"],
    dayInLife: [
      "Review campaign performance dashboards",
      "Brief creative on a new launch",
      "Cross-functional sync with sales and product",
      "Approve budget and channel allocation",
    ],
    topTasks: [
      "Estimate demand for products and services",
      "Develop pricing strategies",
      "Initiate market research studies",
    ],
  },
  {
    slug: "graphic-designer",
    title: "Graphic Designer",
    soc: "27-1024",
    shortDescription: "Communicate visually — branding, marketing, editorial, packaging. Portfolio is everything.",
    medianSalary: 58910,
    salaryP10: 38110,
    salaryP90: 100450,
    outlookPct: 3,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree or strong portfolio",
    relatedMajorSlugs: ["graphic-design", "communications"],
    dayInLife: [
      "Kickoff meeting on a new brand identity",
      "Sketch and iterate on logo concepts",
      "Refine in Figma or Adobe Illustrator",
      "Present options to the client",
    ],
    topTasks: [
      "Meet with clients or the art director to determine scope",
      "Create designs either by hand or using software",
      "Present design concepts for feedback",
    ],
  },
  {
    slug: "ux-designer",
    title: "UX / UI Designer",
    soc: "27-1014",
    shortDescription: "Design how software feels to use. Research users, prototype flows, partner with engineers.",
    medianSalary: 98540,
    salaryP10: 58180,
    salaryP90: 161760,
    outlookPct: 16,
    outlookLabel: "much-faster",
    educationRequired: "Bachelor's degree or strong portfolio",
    relatedMajorSlugs: ["graphic-design", "computer-science", "psychology"],
    dayInLife: [
      "User interview or usability test",
      "Wireframe a flow in Figma",
      "Design review with PM and engineering",
      "Update the design system",
    ],
    topTasks: [
      "Conduct user research and testing",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Collaborate with engineering on implementation",
    ],
  },
  {
    slug: "journalist",
    title: "Journalist / Reporter",
    soc: "27-3023",
    shortDescription: "Report the news — print, digital, broadcast. Tough market, high impact.",
    medianSalary: 57500,
    salaryP10: 34790,
    salaryP90: 129160,
    outlookPct: -3,
    outlookLabel: "declining",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["communications", "political-science"],
    dayInLife: [
      "Chase a lead — phone calls, emails, source meetings",
      "Write and file a story before deadline",
      "Pitch new ideas to your editor",
    ],
    topTasks: [
      "Research news stories and verify facts",
      "Interview sources",
      "Write articles for publication or broadcast",
    ],
  },
  {
    slug: "social-media-manager",
    title: "Social Media Manager",
    soc: "13-1161",
    shortDescription: "Plan and run a brand's presence across platforms. Part strategy, part content, part analytics.",
    medianSalary: 75440,
    salaryP10: 40240,
    salaryP90: 140040,
    outlookPct: 6,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["communications", "business"],
    dayInLife: [
      "Review yesterday's post performance",
      "Shoot and edit short-form video",
      "Plan next week's content calendar",
      "Reply to comments and DMs",
    ],
    topTasks: [
      "Plan content across social channels",
      "Monitor engagement and analytics",
      "Coordinate with creative and PR teams",
    ],
  },
  {
    slug: "teacher-k12",
    title: "K-12 Teacher",
    soc: "25-2021",
    shortDescription: "Teach elementary, middle, or high school students. Deep impact; modest pay by sector.",
    medianSalary: 63670,
    salaryP10: 45060,
    salaryP90: 104070,
    outlookPct: 1,
    outlookLabel: "slower",
    educationRequired: "Bachelor's + state license",
    relatedMajorSlugs: ["education"],
    dayInLife: [
      "Lead 4–5 class periods",
      "Plan lessons during prep period",
      "Grade and give feedback in the evening",
      "Run clubs or coach after school",
    ],
    topTasks: [
      "Plan lessons aligned to standards",
      "Evaluate students' progress",
      "Work with students individually to help them overcome learning difficulties",
    ],
  },
  {
    slug: "school-counselor",
    title: "School Counselor",
    soc: "21-1012",
    shortDescription: "Support students through academic planning, college prep, and emotional wellbeing.",
    medianSalary: 61710,
    salaryP10: 38350,
    salaryP90: 100050,
    outlookPct: 5,
    outlookLabel: "average",
    educationRequired: "Master's in counseling",
    relatedMajorSlugs: ["psychology", "education", "social-work"],
    dayInLife: [
      "Meet with students 1:1 on college plans",
      "Classroom presentation on study skills",
      "Coordinate with parents and teachers",
    ],
    topTasks: [
      "Evaluate students' abilities, interests, and personalities",
      "Help students develop academic plans",
      "Refer students to specialists as needed",
    ],
  },
  {
    slug: "clinical-psychologist",
    title: "Clinical Psychologist",
    soc: "19-3033",
    shortDescription: "Assess and treat mental health conditions. Requires a doctorate; high autonomy.",
    medianSalary: 92740,
    salaryP10: 53780,
    salaryP90: 157420,
    outlookPct: 6,
    outlookLabel: "average",
    educationRequired: "PhD or PsyD",
    relatedMajorSlugs: ["psychology"],
    dayInLife: [
      "See 6–8 therapy clients",
      "Write session notes and treatment plans",
      "Supervise trainees or consult with colleagues",
    ],
    topTasks: [
      "Identify psychological and behavioral issues",
      "Diagnose disorders",
      "Develop and carry out treatment plans",
    ],
  },
  {
    slug: "social-worker",
    title: "Social Worker",
    soc: "21-1029",
    shortDescription: "Help individuals, families, and communities cope with challenges. Clinical or community focus.",
    medianSalary: 58380,
    salaryP10: 37660,
    salaryP90: 94910,
    outlookPct: 7,
    outlookLabel: "faster",
    educationRequired: "Bachelor's or master's (MSW)",
    relatedMajorSlugs: ["social-work", "psychology"],
    dayInLife: [
      "Home or school visits with clients",
      "Case notes and care coordination",
      "Advocate with services, schools, and courts",
    ],
    topTasks: [
      "Identify people who need help",
      "Assess clients' needs, situations, and support networks",
      "Develop plans to improve clients' well-being",
    ],
  },
  {
    slug: "lawyer",
    title: "Lawyer",
    soc: "23-1011",
    shortDescription: "Advise and represent clients on legal matters — corporate, public interest, litigation, and more.",
    medianSalary: 145760,
    salaryP10: 69860,
    salaryP90: 239200,
    outlookPct: 8,
    outlookLabel: "faster",
    educationRequired: "JD + bar exam",
    relatedMajorSlugs: ["political-science", "business"],
    dayInLife: [
      "Research case law and draft briefs",
      "Meetings with clients and opposing counsel",
      "Court appearance or deposition",
    ],
    topTasks: [
      "Advise and represent clients",
      "Research and analyze legal problems",
      "Prepare and file legal documents",
    ],
  },
  {
    slug: "police-officer",
    title: "Police Officer",
    soc: "33-3051",
    shortDescription: "Patrol, respond to calls, investigate, and protect. Paid on-the-job academy training.",
    medianSalary: 72280,
    salaryP10: 46060,
    salaryP90: 113860,
    outlookPct: 3,
    outlookLabel: "average",
    educationRequired: "High school + academy (degree helps)",
    relatedMajorSlugs: ["criminal-justice", "political-science"],
    dayInLife: [
      "Patrol assigned area, respond to dispatch calls",
      "Write reports and interview witnesses",
      "Court testimony on past cases",
    ],
    topTasks: [
      "Enforce laws",
      "Respond to emergency and nonemergency calls",
      "Conduct traffic stops and issue citations",
    ],
  },
  {
    slug: "environmental-scientist",
    title: "Environmental Scientist",
    soc: "19-2041",
    shortDescription: "Study how ecosystems, pollutants, and climate interact — fieldwork + lab + data + policy.",
    medianSalary: 78980,
    salaryP10: 48380,
    salaryP90: 133660,
    outlookPct: 6,
    outlookLabel: "average",
    educationRequired: "Bachelor's degree",
    relatedMajorSlugs: ["environmental-science", "biology"],
    dayInLife: [
      "Site visit to collect water or soil samples",
      "Lab analysis and data cleanup",
      "Write reports for clients or regulators",
    ],
    topTasks: [
      "Collect environmental data",
      "Analyze samples and survey results",
      "Develop plans to prevent or control pollution",
    ],
  },
  {
    slug: "architect",
    title: "Architect",
    soc: "17-1011",
    shortDescription: "Design buildings — from homes to skyscrapers. Long licensure path (5 years + exams).",
    medianSalary: 93310,
    salaryP10: 55210,
    salaryP90: 147100,
    outlookPct: 5,
    outlookLabel: "average",
    educationRequired: "B.Arch or M.Arch + ARE exams",
    relatedMajorSlugs: ["architecture"],
    dayInLife: [
      "Sketch or model a new concept",
      "Meet with clients to review options",
      "Coordinate with engineers and contractors",
      "Site visits during construction",
    ],
    topTasks: [
      "Meet with clients to determine requirements",
      "Give preliminary estimates on cost and construction time",
      "Prepare structure specifications",
    ],
  },
  {
    slug: "film-director",
    title: "Film / Video Director",
    soc: "27-2012",
    shortDescription: "Lead the creative vision of films, shows, and commercials. Freelance, highly competitive.",
    medianSalary: 85320,
    salaryP10: 40040,
    salaryP90: 210680,
    outlookPct: 7,
    outlookLabel: "faster",
    educationRequired: "Bachelor's or working experience",
    relatedMajorSlugs: ["film", "communications"],
    dayInLife: [
      "Shot list and blocking for the day",
      "Direct actors between takes",
      "Work with DP and editor on the look",
    ],
    topTasks: [
      "Oversee production and filming",
      "Direct actors, camera operators, and crew",
      "Select scripts and make creative decisions",
    ],
  },
  {
    slug: "musician",
    title: "Musician / Music Producer",
    soc: "27-2042",
    shortDescription: "Perform, compose, produce, or teach music. Often freelance; income varies widely.",
    medianSalary: 39000,
    salaryP10: 18720,
    salaryP90: 78700,
    outlookPct: 2,
    outlookLabel: "slower",
    educationRequired: "Varies — lessons to conservatory",
    relatedMajorSlugs: ["music"],
    dayInLife: [
      "Practice or rehearse with your group",
      "Perform live or record in-studio",
      "Teach private lessons or run sessions",
    ],
    topTasks: [
      "Perform music for live or recorded audiences",
      "Practice playing instruments or singing",
      "Compose or arrange music",
    ],
  },
  {
    slug: "foreign-service-officer",
    title: "Foreign Service Officer / Diplomat",
    soc: "19-3094",
    shortDescription: "Represent the US abroad at embassies and consulates — political, economic, consular work.",
    medianSalary: 92000,
    salaryP10: 58000,
    salaryP90: 155000,
    outlookPct: 4,
    outlookLabel: "average",
    educationRequired: "Bachelor's + Foreign Service exam",
    relatedMajorSlugs: ["international-relations", "political-science"],
    dayInLife: [
      "Draft a reporting cable on local politics",
      "Meet with local officials or civil society",
      "Process visa interviews at the consulate",
    ],
    topTasks: [
      "Analyze political, economic, and social conditions",
      "Represent US interests abroad",
      "Provide services to US citizens overseas",
    ],
  },
  {
    slug: "athletic-trainer",
    title: "Athletic Trainer / Coach",
    soc: "29-9091",
    shortDescription: "Prevent, diagnose, and rehab sports injuries. Work with teams at all levels.",
    medianSalary: 57930,
    salaryP10: 41670,
    salaryP90: 84010,
    outlookPct: 14,
    outlookLabel: "faster",
    educationRequired: "Bachelor's + BOC certification",
    relatedMajorSlugs: ["sports-management", "biology"],
    dayInLife: [
      "Pre-practice taping and warmups",
      "Injury assessment and rehab sessions",
      "Coordinate with team physician",
    ],
    topTasks: [
      "Evaluate athletes' readiness to play",
      "Provide first aid or emergency care",
      "Develop and carry out rehabilitation programs",
    ],
  },
  {
    slug: "research-scientist",
    title: "Research Scientist",
    soc: "19-1029",
    shortDescription: "Run experiments to advance knowledge in biology, chemistry, neuroscience, or applied fields.",
    medianSalary: 95310,
    salaryP10: 54610,
    salaryP90: 163780,
    outlookPct: 7,
    outlookLabel: "faster",
    educationRequired: "PhD typical in academia; master's in industry",
    relatedMajorSlugs: ["biology", "environmental-science", "data-science"],
    dayInLife: [
      "Run bench experiments or analyse data",
      "Lab meeting to discuss results",
      "Write a paper, grant, or patent",
    ],
    topTasks: [
      "Design and conduct experiments",
      "Analyze data and publish findings",
      "Apply for research funding",
    ],
  },
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    soc: "15-1212",
    shortDescription: "Defend organizations from attacks — monitoring, incident response, architecture.",
    medianSalary: 120360,
    salaryP10: 69210,
    salaryP90: 182370,
    outlookPct: 32,
    outlookLabel: "much-faster",
    educationRequired: "Bachelor's degree + certifications",
    relatedMajorSlugs: ["computer-science", "data-science"],
    dayInLife: [
      "Review overnight alerts from the SIEM",
      "Triage an incident and write a postmortem",
      "Harden systems and update playbooks",
    ],
    topTasks: [
      "Monitor networks for security breaches",
      "Investigate security incidents",
      "Develop security standards and best practices",
    ],
  },
  {
    slug: "ai-ml-engineer",
    title: "AI / Machine Learning Engineer",
    soc: "15-1255",
    shortDescription: "Build and deploy ML systems at scale. One of the highest-paid tracks in tech.",
    medianSalary: 145080,
    salaryP10: 80820,
    salaryP90: 221730,
    outlookPct: 26,
    outlookLabel: "much-faster",
    educationRequired: "Bachelor's or master's",
    relatedMajorSlugs: ["computer-science", "data-science", "engineering"],
    dayInLife: [
      "Clean training data and tune a model",
      "Set up evaluation harness and run experiments",
      "Partner with infra to deploy to production",
    ],
    topTasks: [
      "Develop and train machine-learning models",
      "Integrate ML services into applications",
      "Evaluate model performance against business metrics",
    ],
  },
];

export function getCareerBySlug(slug: string): Career | undefined {
  return CAREERS.find((c) => c.slug === slug);
}

export function careersForMajor(majorSlug: string): Career[] {
  return CAREERS.filter((c) => c.relatedMajorSlugs.includes(majorSlug));
}

export const ALL_MAJOR_SLUGS = Array.from(
  new Set(CAREERS.flatMap((c) => c.relatedMajorSlugs))
).sort();
