import { College } from "./types";

type CollegeSeed = Omit<College, "last_updated"> & { official_url?: string };

export const COLLEGES_SEED: CollegeSeed[] = [
  // ── Ivy League ──────────────────────────────────────────────
  {
    slug: "harvard-university",
    name: "Harvard University",
    location: "Cambridge, MA",
    state: "MA",
    acceptance_rate: 3.2,
    avg_cost_instate: 57261,
    avg_cost_outstate: 57261,
    graduation_rate: 98,
    total_enrollment: 31345,
    photo_url:
      "https://images.unsplash.com/photo-1583373834259-46cc92173cb7?w=800&q=80",
    official_url: "https://www.harvard.edu",
    programs: [
      "Economics",
      "Computer Science",
      "Political Science",
      "Biology",
      "Mathematics",
      "History",
      "English",
      "Psychology",
    ],
  },
  {
    slug: "yale-university",
    name: "Yale University",
    location: "New Haven, CT",
    state: "CT",
    acceptance_rate: 4.4,
    avg_cost_instate: 62250,
    avg_cost_outstate: 62250,
    graduation_rate: 97,
    total_enrollment: 14776,
    photo_url:
      "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80",
    official_url: "https://www.yale.edu",
    programs: [
      "Economics",
      "Political Science",
      "History",
      "Molecular Biology",
      "Computer Science",
      "Psychology",
      "English",
      "Art",
    ],
  },
  {
    slug: "princeton-university",
    name: "Princeton University",
    location: "Princeton, NJ",
    state: "NJ",
    acceptance_rate: 3.7,
    avg_cost_instate: 59710,
    avg_cost_outstate: 59710,
    graduation_rate: 97,
    total_enrollment: 8623,
    photo_url:
      "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&q=80",
    official_url: "https://www.princeton.edu",
    programs: [
      "Computer Science",
      "Economics",
      "Public Policy",
      "Engineering",
      "Mathematics",
      "Physics",
      "History",
      "Philosophy",
    ],
  },
  {
    slug: "columbia-university",
    name: "Columbia University",
    location: "New York, NY",
    state: "NY",
    acceptance_rate: 3.9,
    avg_cost_instate: 65524,
    avg_cost_outstate: 65524,
    graduation_rate: 95,
    total_enrollment: 36649,
    photo_url:
      "https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=800&q=80",
    official_url: "https://www.columbia.edu",
    programs: [
      "Computer Science",
      "Economics",
      "Political Science",
      "Engineering",
      "English",
      "History",
      "Neuroscience",
      "Film Studies",
    ],
  },

  // ── Top Public Universities ─────────────────────────────────
  {
    slug: "uc-berkeley",
    name: "University of California, Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    acceptance_rate: 11.6,
    avg_cost_instate: 15602,
    avg_cost_outstate: 46326,
    graduation_rate: 93,
    total_enrollment: 45307,
    photo_url:
      "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80",
    official_url: "https://www.berkeley.edu",
    programs: [
      "Computer Science",
      "Electrical Engineering",
      "Business",
      "Biology",
      "Economics",
      "Data Science",
      "Environmental Science",
      "Chemistry",
    ],
  },
  {
    slug: "ucla",
    name: "University of California, Los Angeles",
    location: "Los Angeles, CA",
    state: "CA",
    acceptance_rate: 8.6,
    avg_cost_instate: 14312,
    avg_cost_outstate: 44830,
    graduation_rate: 92,
    total_enrollment: 47310,
    photo_url:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    official_url: "https://www.ucla.edu",
    programs: [
      "Biology",
      "Psychology",
      "Political Science",
      "Economics",
      "Film & Television",
      "Nursing",
      "Computer Science",
      "Communications",
    ],
  },
  {
    slug: "university-of-michigan",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    state: "MI",
    acceptance_rate: 17.7,
    avg_cost_instate: 17786,
    avg_cost_outstate: 57762,
    graduation_rate: 93,
    total_enrollment: 48090,
    photo_url:
      "https://images.unsplash.com/photo-1598618443855-232ee0f819f6?w=800&q=80",
    official_url: "https://umich.edu",
    programs: [
      "Engineering",
      "Business",
      "Computer Science",
      "Economics",
      "Psychology",
      "Nursing",
      "Public Policy",
      "Kinesiology",
    ],
  },
  {
    slug: "university-of-virginia",
    name: "University of Virginia",
    location: "Charlottesville, VA",
    state: "VA",
    acceptance_rate: 16.3,
    avg_cost_instate: 21426,
    avg_cost_outstate: 57222,
    graduation_rate: 94,
    total_enrollment: 26082,
    photo_url:
      "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1920&q=80",
    official_url: "https://www.virginia.edu",
    programs: [
      "Commerce",
      "Economics",
      "Biology",
      "Computer Science",
      "Engineering",
      "History",
      "Government",
      "Nursing",
    ],
  },
  {
    slug: "unc-chapel-hill",
    name: "University of North Carolina at Chapel Hill",
    location: "Chapel Hill, NC",
    state: "NC",
    acceptance_rate: 16.8,
    avg_cost_instate: 9021,
    avg_cost_outstate: 38562,
    graduation_rate: 91,
    total_enrollment: 32575,
    photo_url:
      "https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=1920&q=80",
    official_url: "https://www.unc.edu",
    programs: [
      "Biology",
      "Business",
      "Computer Science",
      "Nursing",
      "Media & Journalism",
      "Political Science",
      "Psychology",
      "Public Health",
    ],
  },
  {
    slug: "ut-austin",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    state: "TX",
    acceptance_rate: 31.8,
    avg_cost_instate: 11448,
    avg_cost_outstate: 41070,
    graduation_rate: 88,
    total_enrollment: 53082,
    photo_url:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    official_url: "https://www.utexas.edu",
    programs: [
      "Business",
      "Engineering",
      "Computer Science",
      "Communications",
      "Biology",
      "Economics",
      "Nursing",
      "Architecture",
    ],
  },
  {
    slug: "georgia-tech",
    name: "Georgia Institute of Technology",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 16.0,
    avg_cost_instate: 12682,
    avg_cost_outstate: 37600,
    graduation_rate: 92,
    total_enrollment: 47000,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=80",
    official_url: "https://www.gatech.edu",
    programs: [
      "Computer Science",
      "Mechanical Engineering",
      "Industrial Engineering",
      "Biomedical Engineering",
      "Electrical Engineering",
      "Business",
      "Architecture",
      "Physics",
    ],
  },

  // ── Large State Universities ────────────────────────────────
  {
    slug: "ohio-state-university",
    name: "Ohio State University",
    location: "Columbus, OH",
    state: "OH",
    acceptance_rate: 53.0,
    avg_cost_instate: 12485,
    avg_cost_outstate: 36722,
    graduation_rate: 83,
    total_enrollment: 61369,
    photo_url:
      "https://images.unsplash.com/photo-1543505298-b8be9b0e5e4d?w=1920&q=80",
    official_url: "https://www.osu.edu",
    programs: [
      "Business",
      "Engineering",
      "Biology",
      "Psychology",
      "Nursing",
      "Communication",
      "Computer Science",
      "Agriculture",
    ],
  },
  {
    slug: "penn-state",
    name: "Pennsylvania State University",
    location: "University Park, PA",
    state: "PA",
    acceptance_rate: 55.0,
    avg_cost_instate: 19286,
    avg_cost_outstate: 38824,
    graduation_rate: 86,
    total_enrollment: 88502,
    photo_url:
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=1920&q=80",
    official_url: "https://www.psu.edu",
    programs: [
      "Engineering",
      "Business",
      "Agriculture",
      "Biology",
      "Kinesiology",
      "Computer Science",
      "Communications",
      "Education",
    ],
  },
  {
    slug: "university-of-florida",
    name: "University of Florida",
    location: "Gainesville, FL",
    state: "FL",
    acceptance_rate: 23.0,
    avg_cost_instate: 6381,
    avg_cost_outstate: 28658,
    graduation_rate: 90,
    total_enrollment: 55211,
    photo_url:
      "https://images.unsplash.com/photo-1535957998253-26ae1ef29506?w=1920&q=80",
    official_url: "https://www.ufl.edu",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Computer Science",
      "Journalism",
      "Agriculture",
      "Health Science",
      "Psychology",
    ],
  },
  {
    slug: "arizona-state-university",
    name: "Arizona State University",
    location: "Tempe, AZ",
    state: "AZ",
    acceptance_rate: 88.0,
    avg_cost_instate: 12447,
    avg_cost_outstate: 31200,
    graduation_rate: 69,
    total_enrollment: 78254,
    photo_url:
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1920&q=80",
    official_url: "https://www.asu.edu",
    programs: [
      "Business",
      "Engineering",
      "Sustainability",
      "Computer Science",
      "Journalism",
      "Education",
      "Criminal Justice",
      "Nursing",
    ],
  },
  {
    slug: "florida-state-university",
    name: "Florida State University",
    location: "Tallahassee, FL",
    state: "FL",
    acceptance_rate: 25.0,
    avg_cost_instate: 6517,
    avg_cost_outstate: 21683,
    graduation_rate: 83,
    total_enrollment: 44862,
    photo_url:
      "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=1920&q=80",
    official_url: "https://www.fsu.edu",
    programs: [
      "Business",
      "Criminology",
      "Biology",
      "Psychology",
      "Film",
      "Music",
      "Engineering",
      "Education",
    ],
  },

  // ── Mid-Range Universities ──────────────────────────────────
  {
    slug: "james-madison-university",
    name: "James Madison University",
    location: "Harrisonburg, VA",
    state: "VA",
    acceptance_rate: 72.0,
    avg_cost_instate: 12488,
    avg_cost_outstate: 29602,
    graduation_rate: 82,
    total_enrollment: 22825,
    photo_url:
      "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=1920&q=80",
    official_url: "https://www.jmu.edu",
    programs: [
      "Health Sciences",
      "Business",
      "Biology",
      "Communication",
      "Nursing",
      "Kinesiology",
      "Education",
      "Computer Science",
    ],
  },
  {
    slug: "clemson-university",
    name: "Clemson University",
    location: "Clemson, SC",
    state: "SC",
    acceptance_rate: 43.0,
    avg_cost_instate: 16178,
    avg_cost_outstate: 40794,
    graduation_rate: 84,
    total_enrollment: 28466,
    photo_url:
      "https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=1920&q=80",
    official_url: "https://www.clemson.edu",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Nursing",
      "Agriculture",
      "Architecture",
      "Computer Science",
      "Parks & Recreation",
    ],
  },
  {
    slug: "boise-state-university",
    name: "Boise State University",
    location: "Boise, ID",
    state: "ID",
    acceptance_rate: 83.0,
    avg_cost_instate: 8832,
    avg_cost_outstate: 25706,
    graduation_rate: 52,
    total_enrollment: 26067,
    photo_url:
      "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1920&q=80",
    official_url: "https://www.boisestate.edu",
    programs: [
      "Business",
      "Health Science",
      "Engineering",
      "Nursing",
      "Education",
      "Criminal Justice",
      "Computer Science",
      "Kinesiology",
    ],
  },
  {
    slug: "iowa-state-university",
    name: "Iowa State University",
    location: "Ames, IA",
    state: "IA",
    acceptance_rate: 91.0,
    avg_cost_instate: 10264,
    avg_cost_outstate: 25976,
    graduation_rate: 76,
    total_enrollment: 30708,
    photo_url:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1920&q=80",
    official_url: "https://www.iastate.edu",
    programs: [
      "Engineering",
      "Agriculture",
      "Business",
      "Biology",
      "Computer Science",
      "Veterinary Medicine",
      "Design",
      "Education",
    ],
  },

  // ── Liberal Arts Colleges ───────────────────────────────────
  {
    slug: "williams-college",
    name: "Williams College",
    location: "Williamstown, MA",
    state: "MA",
    acceptance_rate: 8.5,
    avg_cost_instate: 63450,
    avg_cost_outstate: 63450,
    graduation_rate: 96,
    total_enrollment: 2089,
    photo_url:
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1920&q=80",
    official_url: "https://www.williams.edu",
    programs: [
      "Economics",
      "Mathematics",
      "English",
      "Psychology",
      "Art History",
      "Biology",
      "Political Science",
      "Philosophy",
    ],
  },
  {
    slug: "amherst-college",
    name: "Amherst College",
    location: "Amherst, MA",
    state: "MA",
    acceptance_rate: 7.3,
    avg_cost_instate: 65100,
    avg_cost_outstate: 65100,
    graduation_rate: 95,
    total_enrollment: 1971,
    photo_url:
      "https://images.unsplash.com/photo-1592495981488-073153776d9a?w=1920&q=80",
    official_url: "https://www.amherst.edu",
    programs: [
      "Economics",
      "Mathematics",
      "English",
      "Political Science",
      "Psychology",
      "Biology",
      "Computer Science",
      "Law & Jurisprudence",
    ],
  },
  {
    slug: "bowdoin-college",
    name: "Bowdoin College",
    location: "Brunswick, ME",
    state: "ME",
    acceptance_rate: 8.7,
    avg_cost_instate: 64120,
    avg_cost_outstate: 64120,
    graduation_rate: 95,
    total_enrollment: 1878,
    photo_url:
      "https://images.unsplash.com/photo-1580977276076-ae4b8c219b8e?w=1920&q=80",
    official_url: "https://www.bowdoin.edu",
    programs: [
      "Government",
      "Economics",
      "Mathematics",
      "Biology",
      "English",
      "Earth & Oceanographic Science",
      "Computer Science",
      "Neuroscience",
    ],
  },

  // ── HBCUs ──────────────────────────────────────────────────
  {
    slug: "howard-university",
    name: "Howard University",
    location: "Washington, DC",
    state: "DC",
    acceptance_rate: 30.0,
    avg_cost_instate: 32053,
    avg_cost_outstate: 32053,
    graduation_rate: 66,
    total_enrollment: 12753,
    photo_url:
      "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=1920&q=80",
    official_url: "https://www.howard.edu",
    programs: [
      "Biology",
      "Nursing",
      "Business",
      "Communications",
      "Political Science",
      "Psychology",
      "Engineering",
      "African American Studies",
    ],
  },
  {
    slug: "spelman-college",
    name: "Spelman College",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 29.0,
    avg_cost_instate: 31962,
    avg_cost_outstate: 31962,
    graduation_rate: 77,
    total_enrollment: 2264,
    photo_url:
      "https://images.unsplash.com/photo-1607013407627-6848f64e5fa4?w=1920&q=80",
    official_url: "https://www.spelman.edu",
    programs: [
      "Biology",
      "Psychology",
      "Political Science",
      "English",
      "Computer Science",
      "Economics",
      "Sociology",
      "Health Sciences",
    ],
  },
  {
    slug: "morehouse-college",
    name: "Morehouse College",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 39.0,
    avg_cost_instate: 30342,
    avg_cost_outstate: 30342,
    graduation_rate: 60,
    total_enrollment: 2256,
    photo_url:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1920&q=80",
    official_url: "https://www.morehouse.edu",
    programs: [
      "Business Administration",
      "Biology",
      "Computer Science",
      "Political Science",
      "Psychology",
      "Cinema & Media Studies",
      "Engineering",
      "Kinesiology",
    ],
  },

  // ── Technical Institutions ──────────────────────────────────
  {
    slug: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    state: "MA",
    acceptance_rate: 3.5,
    avg_cost_instate: 61990,
    avg_cost_outstate: 61990,
    graduation_rate: 96,
    total_enrollment: 11858,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.mit.edu",
    programs: [
      "Computer Science",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Mathematics",
      "Physics",
      "Biology",
      "Economics",
      "Architecture",
    ],
  },
  {
    slug: "caltech",
    name: "California Institute of Technology",
    location: "Pasadena, CA",
    state: "CA",
    acceptance_rate: 2.7,
    avg_cost_instate: 63471,
    avg_cost_outstate: 63471,
    graduation_rate: 94,
    total_enrollment: 2397,
    photo_url:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1920&q=80",
    official_url: "https://www.caltech.edu",
    programs: [
      "Physics",
      "Computer Science",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Astrophysics",
    ],
  },
  {
    slug: "rpi",
    name: "Rensselaer Polytechnic Institute",
    location: "Troy, NY",
    state: "NY",
    acceptance_rate: 57.0,
    avg_cost_instate: 60551,
    avg_cost_outstate: 60551,
    graduation_rate: 86,
    total_enrollment: 7762,
    photo_url:
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1920&q=80",
    official_url: "https://www.rpi.edu",
    programs: [
      "Computer Science",
      "Engineering",
      "Business",
      "Architecture",
      "Biomedical Engineering",
      "Information Technology",
      "Physics",
      "Game Design",
    ],
  },

  // ── Community Colleges ──────────────────────────────────────
  {
    slug: "santa-monica-college",
    name: "Santa Monica College",
    location: "Santa Monica, CA",
    state: "CA",
    acceptance_rate: 100,
    avg_cost_instate: 1524,
    avg_cost_outstate: 12108,
    graduation_rate: 29,
    total_enrollment: 28000,
    photo_url:
      "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1920&q=80",
    official_url: "https://www.smc.edu",
    programs: [
      "Business",
      "Nursing",
      "Liberal Arts",
      "Computer Science",
      "Film Production",
      "Accounting",
      "Early Childhood Education",
      "Graphic Design",
    ],
  },
  {
    slug: "northern-virginia-community-college",
    name: "Northern Virginia Community College",
    location: "Annandale, VA",
    state: "VA",
    acceptance_rate: 100,
    avg_cost_instate: 6255,
    avg_cost_outstate: 12815,
    graduation_rate: 25,
    total_enrollment: 67000,
    photo_url:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1920&q=80",
    official_url: "https://www.nvcc.edu",
    programs: [
      "Liberal Arts",
      "Business",
      "Information Technology",
      "Engineering",
      "Nursing",
      "Cybersecurity",
      "Education",
      "Health Sciences",
    ],
  },
  {
    slug: "austin-community-college",
    name: "Austin Community College",
    location: "Austin, TX",
    state: "TX",
    acceptance_rate: 100,
    avg_cost_instate: 2970,
    avg_cost_outstate: 10830,
    graduation_rate: 20,
    total_enrollment: 41000,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=80",
    official_url: "https://www.austincc.edu",
    programs: [
      "Business",
      "Computer Science",
      "Nursing",
      "Welding",
      "Veterinary Technology",
      "Culinary Arts",
      "Liberal Arts",
      "Automotive Technology",
    ],
  },

  // ── Expanded: Missouri & Midwest ───────────────────────────
  {
    slug: "university-of-missouri",
    name: "University of Missouri",
    location: "Columbia, MO",
    state: "MO",
    acceptance_rate: 82.0,
    avg_cost_instate: 11836,
    avg_cost_outstate: 29436,
    graduation_rate: 72,
    total_enrollment: 31103,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://missouri.edu",
    programs: [
      "Journalism",
      "Business",
      "Engineering",
      "Agriculture",
      "Health Sciences",
      "Education",
      "Biology",
      "Computer Science",
    ],
  },
  {
    slug: "missouri-state-university",
    name: "Missouri State University",
    location: "Springfield, MO",
    state: "MO",
    acceptance_rate: 84.0,
    avg_cost_instate: 8888,
    avg_cost_outstate: 19338,
    graduation_rate: 56,
    total_enrollment: 22394,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.missouristate.edu",
    programs: [
      "Business",
      "Education",
      "Health Sciences",
      "Biology",
      "Psychology",
      "Criminal Justice",
      "Nursing",
      "Communication",
    ],
  },
  {
    slug: "washington-university-in-st-louis",
    name: "Washington University in St. Louis",
    location: "St. Louis, MO",
    state: "MO",
    acceptance_rate: 11.0,
    avg_cost_instate: 63373,
    avg_cost_outstate: 63373,
    graduation_rate: 95,
    total_enrollment: 16275,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://wustl.edu",
    programs: [
      "Business",
      "Computer Science",
      "Biology",
      "Engineering",
      "Medicine",
      "Political Science",
      "Psychology",
      "Architecture",
    ],
  },
  {
    slug: "saint-louis-university",
    name: "Saint Louis University",
    location: "St. Louis, MO",
    state: "MO",
    acceptance_rate: 58.0,
    avg_cost_instate: 50644,
    avg_cost_outstate: 50644,
    graduation_rate: 76,
    total_enrollment: 12564,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.slu.edu",
    programs: [
      "Nursing",
      "Business",
      "Biology",
      "Health Sciences",
      "Engineering",
      "Psychology",
      "Aviation",
      "Public Health",
    ],
  },
  {
    slug: "truman-state-university",
    name: "Truman State University",
    location: "Kirksville, MO",
    state: "MO",
    acceptance_rate: 72.0,
    avg_cost_instate: 9052,
    avg_cost_outstate: 16392,
    graduation_rate: 72,
    total_enrollment: 5500,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.truman.edu",
    programs: [
      "Biology",
      "Business",
      "Exercise Science",
      "Psychology",
      "English",
      "Nursing",
      "Chemistry",
      "Education",
    ],
  },

  // ── Expanded: Plains States ────────────────────────────────
  {
    slug: "university-of-kansas",
    name: "University of Kansas",
    location: "Lawrence, KS",
    state: "KS",
    acceptance_rate: 88.0,
    avg_cost_instate: 11166,
    avg_cost_outstate: 28926,
    graduation_rate: 67,
    total_enrollment: 27638,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.ku.edu",
    programs: [
      "Business",
      "Pharmacy",
      "Engineering",
      "Journalism",
      "Biology",
      "Education",
      "Psychology",
      "Architecture",
    ],
  },
  {
    slug: "kansas-state-university",
    name: "Kansas State University",
    location: "Manhattan, KS",
    state: "KS",
    acceptance_rate: 94.0,
    avg_cost_instate: 10814,
    avg_cost_outstate: 27060,
    graduation_rate: 65,
    total_enrollment: 20660,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.k-state.edu",
    programs: [
      "Agriculture",
      "Engineering",
      "Business",
      "Veterinary Medicine",
      "Architecture",
      "Biology",
      "Education",
      "Computer Science",
    ],
  },
  {
    slug: "university-of-arkansas",
    name: "University of Arkansas",
    location: "Fayetteville, AR",
    state: "AR",
    acceptance_rate: 76.0,
    avg_cost_instate: 10478,
    avg_cost_outstate: 28208,
    graduation_rate: 66,
    total_enrollment: 30936,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uark.edu",
    programs: [
      "Business",
      "Engineering",
      "Agriculture",
      "Architecture",
      "Nursing",
      "Biology",
      "Communications",
      "Education",
    ],
  },
  {
    slug: "university-of-oklahoma",
    name: "University of Oklahoma",
    location: "Norman, OK",
    state: "OK",
    acceptance_rate: 73.0,
    avg_cost_instate: 12018,
    avg_cost_outstate: 29136,
    graduation_rate: 71,
    total_enrollment: 32116,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.ou.edu",
    programs: [
      "Petroleum Engineering",
      "Meteorology",
      "Business",
      "Journalism",
      "Biology",
      "Education",
      "Psychology",
      "Engineering",
    ],
  },
  {
    slug: "oklahoma-state-university",
    name: "Oklahoma State University",
    location: "Stillwater, OK",
    state: "OK",
    acceptance_rate: 75.0,
    avg_cost_instate: 10138,
    avg_cost_outstate: 24738,
    graduation_rate: 62,
    total_enrollment: 24649,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://go.okstate.edu",
    programs: [
      "Agriculture",
      "Engineering",
      "Business",
      "Veterinary Medicine",
      "Education",
      "Aviation",
      "Biology",
      "Computer Science",
    ],
  },
  {
    slug: "university-of-nebraska",
    name: "University of Nebraska",
    location: "Lincoln, NE",
    state: "NE",
    acceptance_rate: 80.0,
    avg_cost_instate: 10610,
    avg_cost_outstate: 27710,
    graduation_rate: 72,
    total_enrollment: 25108,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.unl.edu",
    programs: [
      "Business",
      "Engineering",
      "Agriculture",
      "Education",
      "Journalism",
      "Biology",
      "Computer Science",
      "Architecture",
    ],
  },
  {
    slug: "university-of-iowa",
    name: "University of Iowa",
    location: "Iowa City, IA",
    state: "IA",
    acceptance_rate: 84.0,
    avg_cost_instate: 10710,
    avg_cost_outstate: 32468,
    graduation_rate: 74,
    total_enrollment: 31240,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://uiowa.edu",
    programs: [
      "Creative Writing",
      "Business",
      "Engineering",
      "Nursing",
      "Biology",
      "Psychology",
      "Communications",
      "Health Sciences",
    ],
  },

  // ── Expanded: Upper Midwest ────────────────────────────────
  {
    slug: "university-of-minnesota",
    name: "University of Minnesota",
    location: "Minneapolis, MN",
    state: "MN",
    acceptance_rate: 73.0,
    avg_cost_instate: 15748,
    avg_cost_outstate: 35238,
    graduation_rate: 83,
    total_enrollment: 54117,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://twin-cities.umn.edu",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Psychology",
      "Computer Science",
      "Nursing",
      "Economics",
      "Public Health",
    ],
  },
  {
    slug: "university-of-wisconsin-madison",
    name: "University of Wisconsin-Madison",
    location: "Madison, WI",
    state: "WI",
    acceptance_rate: 49.0,
    avg_cost_instate: 11205,
    avg_cost_outstate: 40603,
    graduation_rate: 89,
    total_enrollment: 49066,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.wisc.edu",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Computer Science",
      "Economics",
      "Political Science",
      "Nursing",
      "Agriculture",
    ],
  },
  {
    slug: "marquette-university",
    name: "Marquette University",
    location: "Milwaukee, WI",
    state: "WI",
    acceptance_rate: 83.0,
    avg_cost_instate: 46950,
    avg_cost_outstate: 46950,
    graduation_rate: 82,
    total_enrollment: 11400,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.marquette.edu",
    programs: [
      "Nursing",
      "Business",
      "Engineering",
      "Health Sciences",
      "Communication",
      "Biology",
      "Psychology",
      "Education",
    ],
  },
  {
    slug: "michigan-state-university",
    name: "Michigan State University",
    location: "East Lansing, MI",
    state: "MI",
    acceptance_rate: 76.0,
    avg_cost_instate: 15372,
    avg_cost_outstate: 42690,
    graduation_rate: 82,
    total_enrollment: 50023,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://msu.edu",
    programs: [
      "Business",
      "Engineering",
      "Education",
      "Agriculture",
      "Criminal Justice",
      "Nursing",
      "Computer Science",
      "Communications",
    ],
  },
  {
    slug: "wayne-state-university",
    name: "Wayne State University",
    location: "Detroit, MI",
    state: "MI",
    acceptance_rate: 75.0,
    avg_cost_instate: 14992,
    avg_cost_outstate: 33208,
    graduation_rate: 45,
    total_enrollment: 23800,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://wayne.edu",
    programs: [
      "Engineering",
      "Nursing",
      "Business",
      "Social Work",
      "Biology",
      "Psychology",
      "Education",
      "Criminal Justice",
    ],
  },

  // ── Expanded: Ohio & Pennsylvania ──────────────────────────
  {
    slug: "university-of-cincinnati",
    name: "University of Cincinnati",
    location: "Cincinnati, OH",
    state: "OH",
    acceptance_rate: 76.0,
    avg_cost_instate: 13424,
    avg_cost_outstate: 28934,
    graduation_rate: 71,
    total_enrollment: 47914,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uc.edu",
    programs: [
      "Engineering",
      "Design",
      "Business",
      "Nursing",
      "Music",
      "Architecture",
      "Biology",
      "Criminal Justice",
    ],
  },
  {
    slug: "case-western-reserve-university",
    name: "Case Western Reserve University",
    location: "Cleveland, OH",
    state: "OH",
    acceptance_rate: 29.0,
    avg_cost_instate: 58264,
    avg_cost_outstate: 58264,
    graduation_rate: 85,
    total_enrollment: 12084,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://case.edu",
    programs: [
      "Engineering",
      "Nursing",
      "Biology",
      "Business",
      "Computer Science",
      "Biomedical Engineering",
      "Psychology",
      "Music",
    ],
  },
  {
    slug: "university-of-pittsburgh",
    name: "University of Pittsburgh",
    location: "Pittsburgh, PA",
    state: "PA",
    acceptance_rate: 57.0,
    avg_cost_instate: 21040,
    avg_cost_outstate: 37482,
    graduation_rate: 83,
    total_enrollment: 34036,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.pitt.edu",
    programs: [
      "Nursing",
      "Engineering",
      "Business",
      "Biology",
      "Philosophy",
      "Computer Science",
      "Health Sciences",
      "Psychology",
    ],
  },
  {
    slug: "temple-university",
    name: "Temple University",
    location: "Philadelphia, PA",
    state: "PA",
    acceptance_rate: 70.0,
    avg_cost_instate: 18988,
    avg_cost_outstate: 34256,
    graduation_rate: 72,
    total_enrollment: 35496,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.temple.edu",
    programs: [
      "Business",
      "Communications",
      "Education",
      "Engineering",
      "Art",
      "Biology",
      "Criminal Justice",
      "Film & Media Arts",
    ],
  },
  {
    slug: "drexel-university",
    name: "Drexel University",
    location: "Philadelphia, PA",
    state: "PA",
    acceptance_rate: 78.0,
    avg_cost_instate: 57136,
    avg_cost_outstate: 57136,
    graduation_rate: 72,
    total_enrollment: 23870,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://drexel.edu",
    programs: [
      "Engineering",
      "Business",
      "Nursing",
      "Computer Science",
      "Design",
      "Biology",
      "Information Science",
      "Health Sciences",
    ],
  },
  {
    slug: "villanova-university",
    name: "Villanova University",
    location: "Villanova, PA",
    state: "PA",
    acceptance_rate: 23.0,
    avg_cost_instate: 61964,
    avg_cost_outstate: 61964,
    graduation_rate: 92,
    total_enrollment: 10659,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www1.villanova.edu",
    programs: [
      "Business",
      "Engineering",
      "Nursing",
      "Biology",
      "Communication",
      "Political Science",
      "Finance",
      "Computer Science",
    ],
  },

  // ── Expanded: Mid-Atlantic ─────────────────────────────────
  {
    slug: "university-of-delaware",
    name: "University of Delaware",
    location: "Newark, DE",
    state: "DE",
    acceptance_rate: 66.0,
    avg_cost_instate: 15470,
    avg_cost_outstate: 38230,
    graduation_rate: 80,
    total_enrollment: 24437,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.udel.edu",
    programs: [
      "Engineering",
      "Business",
      "Nursing",
      "Education",
      "Biology",
      "Chemical Engineering",
      "Communication",
      "Hotel Management",
    ],
  },
  {
    slug: "university-of-maryland",
    name: "University of Maryland",
    location: "College Park, MD",
    state: "MD",
    acceptance_rate: 44.0,
    avg_cost_instate: 11564,
    avg_cost_outstate: 39700,
    graduation_rate: 87,
    total_enrollment: 41200,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.umd.edu",
    programs: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Criminology",
      "Economics",
      "Journalism",
      "Information Science",
    ],
  },
  {
    slug: "george-mason-university",
    name: "George Mason University",
    location: "Fairfax, VA",
    state: "VA",
    acceptance_rate: 89.0,
    avg_cost_instate: 13362,
    avg_cost_outstate: 37484,
    graduation_rate: 71,
    total_enrollment: 39142,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.gmu.edu",
    programs: [
      "Business",
      "Computer Science",
      "Engineering",
      "Cybersecurity",
      "Biology",
      "Psychology",
      "Communication",
      "Health Administration",
    ],
  },
  {
    slug: "virginia-tech",
    name: "Virginia Tech",
    location: "Blacksburg, VA",
    state: "VA",
    acceptance_rate: 57.0,
    avg_cost_instate: 14626,
    avg_cost_outstate: 35444,
    graduation_rate: 87,
    total_enrollment: 38139,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.vt.edu",
    programs: [
      "Engineering",
      "Business",
      "Agriculture",
      "Architecture",
      "Computer Science",
      "Biology",
      "Veterinary Medicine",
      "Natural Resources",
    ],
  },

  // ── Expanded: Carolinas & Southeast ────────────────────────
  {
    slug: "wake-forest-university",
    name: "Wake Forest University",
    location: "Winston-Salem, NC",
    state: "NC",
    acceptance_rate: 21.0,
    avg_cost_instate: 62294,
    avg_cost_outstate: 62294,
    graduation_rate: 91,
    total_enrollment: 8938,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.wfu.edu",
    programs: [
      "Business",
      "Biology",
      "Communication",
      "Economics",
      "Political Science",
      "Psychology",
      "Computer Science",
      "Health & Exercise Science",
    ],
  },
  {
    slug: "duke-university",
    name: "Duke University",
    location: "Durham, NC",
    state: "NC",
    acceptance_rate: 5.0,
    avg_cost_instate: 63054,
    avg_cost_outstate: 63054,
    graduation_rate: 96,
    total_enrollment: 17620,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://duke.edu",
    programs: [
      "Computer Science",
      "Economics",
      "Public Policy",
      "Biology",
      "Biomedical Engineering",
      "Political Science",
      "Psychology",
      "Neuroscience",
    ],
  },
  {
    slug: "nc-state-university",
    name: "NC State University",
    location: "Raleigh, NC",
    state: "NC",
    acceptance_rate: 47.0,
    avg_cost_instate: 9991,
    avg_cost_outstate: 30869,
    graduation_rate: 81,
    total_enrollment: 37751,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.ncsu.edu",
    programs: [
      "Engineering",
      "Business",
      "Agriculture",
      "Computer Science",
      "Biology",
      "Textiles",
      "Veterinary Medicine",
      "Design",
    ],
  },
  {
    slug: "university-of-south-carolina",
    name: "University of South Carolina",
    location: "Columbia, SC",
    state: "SC",
    acceptance_rate: 68.0,
    avg_cost_instate: 13178,
    avg_cost_outstate: 34566,
    graduation_rate: 77,
    total_enrollment: 35364,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://sc.edu",
    programs: [
      "Business",
      "Nursing",
      "Biology",
      "Engineering",
      "Criminal Justice",
      "International Business",
      "Public Health",
      "Exercise Science",
    ],
  },

  // ── Expanded: Deep South ───────────────────────────────────
  {
    slug: "university-of-alabama",
    name: "University of Alabama",
    location: "Tuscaloosa, AL",
    state: "AL",
    acceptance_rate: 80.0,
    avg_cost_instate: 11580,
    avg_cost_outstate: 32300,
    graduation_rate: 73,
    total_enrollment: 38645,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.ua.edu",
    programs: [
      "Business",
      "Engineering",
      "Nursing",
      "Communications",
      "Biology",
      "Criminal Justice",
      "Education",
      "Computer Science",
    ],
  },
  {
    slug: "auburn-university",
    name: "Auburn University",
    location: "Auburn, AL",
    state: "AL",
    acceptance_rate: 81.0,
    avg_cost_instate: 12268,
    avg_cost_outstate: 33564,
    graduation_rate: 79,
    total_enrollment: 32035,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.auburn.edu",
    programs: [
      "Engineering",
      "Business",
      "Agriculture",
      "Veterinary Medicine",
      "Biology",
      "Nursing",
      "Architecture",
      "Education",
    ],
  },
  {
    slug: "university-of-tennessee",
    name: "University of Tennessee",
    location: "Knoxville, TN",
    state: "TN",
    acceptance_rate: 78.0,
    avg_cost_instate: 13264,
    avg_cost_outstate: 31514,
    graduation_rate: 73,
    total_enrollment: 34425,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.utk.edu",
    programs: [
      "Business",
      "Engineering",
      "Nursing",
      "Agriculture",
      "Biology",
      "Supply Chain Management",
      "Education",
      "Communication",
    ],
  },
  {
    slug: "vanderbilt-university",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    state: "TN",
    acceptance_rate: 5.6,
    avg_cost_instate: 62578,
    avg_cost_outstate: 62578,
    graduation_rate: 95,
    total_enrollment: 13710,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.vanderbilt.edu",
    programs: [
      "Economics",
      "Engineering",
      "Medicine",
      "Education",
      "Music",
      "Political Science",
      "Computer Science",
      "Neuroscience",
    ],
  },
  {
    slug: "university-of-kentucky",
    name: "University of Kentucky",
    location: "Lexington, KY",
    state: "KY",
    acceptance_rate: 90.0,
    avg_cost_instate: 13024,
    avg_cost_outstate: 32318,
    graduation_rate: 68,
    total_enrollment: 31958,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uky.edu",
    programs: [
      "Business",
      "Engineering",
      "Pharmacy",
      "Nursing",
      "Agriculture",
      "Biology",
      "Education",
      "Communication",
    ],
  },
  {
    slug: "university-of-louisville",
    name: "University of Louisville",
    location: "Louisville, KY",
    state: "KY",
    acceptance_rate: 69.0,
    avg_cost_instate: 12324,
    avg_cost_outstate: 29110,
    graduation_rate: 59,
    total_enrollment: 22640,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://louisville.edu",
    programs: [
      "Engineering",
      "Business",
      "Nursing",
      "Biology",
      "Music",
      "Public Health",
      "Computer Science",
      "Education",
    ],
  },

  // ── Expanded: Indiana ──────────────────────────────────────
  {
    slug: "indiana-university",
    name: "Indiana University",
    location: "Bloomington, IN",
    state: "IN",
    acceptance_rate: 80.0,
    avg_cost_instate: 11564,
    avg_cost_outstate: 39184,
    graduation_rate: 79,
    total_enrollment: 47005,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.indiana.edu",
    programs: [
      "Business",
      "Music",
      "Biology",
      "Journalism",
      "Education",
      "Computer Science",
      "Public Health",
      "Informatics",
    ],
  },
  {
    slug: "purdue-university",
    name: "Purdue University",
    location: "West Lafayette, IN",
    state: "IN",
    acceptance_rate: 53.0,
    avg_cost_instate: 10002,
    avg_cost_outstate: 28794,
    graduation_rate: 83,
    total_enrollment: 50884,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.purdue.edu",
    programs: [
      "Engineering",
      "Computer Science",
      "Agriculture",
      "Business",
      "Aviation",
      "Pharmacy",
      "Biology",
      "Nursing",
    ],
  },
  {
    slug: "university-of-notre-dame",
    name: "University of Notre Dame",
    location: "Notre Dame, IN",
    state: "IN",
    acceptance_rate: 12.0,
    avg_cost_instate: 62693,
    avg_cost_outstate: 62693,
    graduation_rate: 97,
    total_enrollment: 13139,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.nd.edu",
    programs: [
      "Business",
      "Engineering",
      "Political Science",
      "Economics",
      "Biology",
      "Computer Science",
      "Theology",
      "Psychology",
    ],
  },

  // ── Expanded: Illinois ─────────────────────────────────────
  {
    slug: "depaul-university",
    name: "DePaul University",
    location: "Chicago, IL",
    state: "IL",
    acceptance_rate: 68.0,
    avg_cost_instate: 43890,
    avg_cost_outstate: 43890,
    graduation_rate: 72,
    total_enrollment: 21157,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.depaul.edu",
    programs: [
      "Business",
      "Computer Science",
      "Psychology",
      "Communication",
      "Accounting",
      "Film & Television",
      "Education",
      "Nursing",
    ],
  },
  {
    slug: "university-of-illinois-chicago",
    name: "University of Illinois Chicago",
    location: "Chicago, IL",
    state: "IL",
    acceptance_rate: 74.0,
    avg_cost_instate: 15222,
    avg_cost_outstate: 28596,
    graduation_rate: 60,
    total_enrollment: 33518,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uic.edu",
    programs: [
      "Engineering",
      "Nursing",
      "Business",
      "Biology",
      "Architecture",
      "Public Health",
      "Computer Science",
      "Psychology",
    ],
  },
  {
    slug: "loyola-university-chicago",
    name: "Loyola University Chicago",
    location: "Chicago, IL",
    state: "IL",
    acceptance_rate: 67.0,
    avg_cost_instate: 50520,
    avg_cost_outstate: 50520,
    graduation_rate: 75,
    total_enrollment: 17007,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.luc.edu",
    programs: [
      "Nursing",
      "Biology",
      "Psychology",
      "Business",
      "Political Science",
      "Education",
      "Social Work",
      "Computer Science",
    ],
  },

  // ── Expanded: Mountain West ────────────────────────────────
  {
    slug: "university-of-denver",
    name: "University of Denver",
    location: "Denver, CO",
    state: "CO",
    acceptance_rate: 65.0,
    avg_cost_instate: 57186,
    avg_cost_outstate: 57186,
    graduation_rate: 80,
    total_enrollment: 11965,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.du.edu",
    programs: [
      "Business",
      "International Studies",
      "Engineering",
      "Psychology",
      "Biology",
      "Computer Science",
      "Music",
      "Hospitality",
    ],
  },
  {
    slug: "university-of-colorado-boulder",
    name: "University of Colorado Boulder",
    location: "Boulder, CO",
    state: "CO",
    acceptance_rate: 80.0,
    avg_cost_instate: 13592,
    avg_cost_outstate: 40488,
    graduation_rate: 74,
    total_enrollment: 40120,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.colorado.edu",
    programs: [
      "Engineering",
      "Business",
      "Environmental Science",
      "Psychology",
      "Biology",
      "Computer Science",
      "Aerospace Engineering",
      "Communications",
    ],
  },
  {
    slug: "colorado-state-university",
    name: "Colorado State University",
    location: "Fort Collins, CO",
    state: "CO",
    acceptance_rate: 84.0,
    avg_cost_instate: 12748,
    avg_cost_outstate: 33046,
    graduation_rate: 70,
    total_enrollment: 33877,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.colostate.edu",
    programs: [
      "Veterinary Medicine",
      "Agriculture",
      "Engineering",
      "Business",
      "Biology",
      "Environmental Science",
      "Computer Science",
      "Health Sciences",
    ],
  },
  {
    slug: "university-of-utah",
    name: "University of Utah",
    location: "Salt Lake City, UT",
    state: "UT",
    acceptance_rate: 86.0,
    avg_cost_instate: 10758,
    avg_cost_outstate: 33036,
    graduation_rate: 69,
    total_enrollment: 34324,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.utah.edu",
    programs: [
      "Business",
      "Engineering",
      "Computer Science",
      "Health Sciences",
      "Biology",
      "Communication",
      "Game Design",
      "Nursing",
    ],
  },
  {
    slug: "university-of-nevada-las-vegas",
    name: "University of Nevada Las Vegas",
    location: "Las Vegas, NV",
    state: "NV",
    acceptance_rate: 85.0,
    avg_cost_instate: 9674,
    avg_cost_outstate: 24144,
    graduation_rate: 47,
    total_enrollment: 30471,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.unlv.edu",
    programs: [
      "Hospitality Management",
      "Business",
      "Engineering",
      "Criminal Justice",
      "Biology",
      "Nursing",
      "Education",
      "Kinesiology",
    ],
  },

  // ── Expanded: Pacific Northwest ────────────────────────────
  {
    slug: "university-of-oregon",
    name: "University of Oregon",
    location: "Eugene, OR",
    state: "OR",
    acceptance_rate: 83.0,
    avg_cost_instate: 13666,
    avg_cost_outstate: 40266,
    graduation_rate: 74,
    total_enrollment: 23634,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uoregon.edu",
    programs: [
      "Journalism",
      "Business",
      "Architecture",
      "Biology",
      "Psychology",
      "Education",
      "Computer Science",
      "Music",
    ],
  },
  {
    slug: "oregon-state-university",
    name: "Oregon State University",
    location: "Corvallis, OR",
    state: "OR",
    acceptance_rate: 82.0,
    avg_cost_instate: 12420,
    avg_cost_outstate: 33132,
    graduation_rate: 68,
    total_enrollment: 34108,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://oregonstate.edu",
    programs: [
      "Engineering",
      "Agriculture",
      "Forestry",
      "Business",
      "Computer Science",
      "Biology",
      "Environmental Science",
      "Veterinary Medicine",
    ],
  },
  {
    slug: "university-of-washington",
    name: "University of Washington",
    location: "Seattle, WA",
    state: "WA",
    acceptance_rate: 48.0,
    avg_cost_instate: 12643,
    avg_cost_outstate: 41997,
    graduation_rate: 85,
    total_enrollment: 61468,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.washington.edu",
    programs: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Nursing",
      "Public Health",
      "Medicine",
      "Environmental Science",
    ],
  },
  {
    slug: "washington-state-university",
    name: "Washington State University",
    location: "Pullman, WA",
    state: "WA",
    acceptance_rate: 83.0,
    avg_cost_instate: 12364,
    avg_cost_outstate: 28354,
    graduation_rate: 62,
    total_enrollment: 31607,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://wsu.edu",
    programs: [
      "Business",
      "Engineering",
      "Agriculture",
      "Nursing",
      "Veterinary Medicine",
      "Criminal Justice",
      "Computer Science",
      "Communication",
    ],
  },

  // ── Expanded: Southwest ────────────────────────────────────
  {
    slug: "university-of-new-mexico",
    name: "University of New Mexico",
    location: "Albuquerque, NM",
    state: "NM",
    acceptance_rate: 96.0,
    avg_cost_instate: 8836,
    avg_cost_outstate: 24796,
    graduation_rate: 52,
    total_enrollment: 24960,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.unm.edu",
    programs: [
      "Engineering",
      "Business",
      "Education",
      "Nursing",
      "Biology",
      "Psychology",
      "Architecture",
      "Latin American Studies",
    ],
  },
  {
    slug: "university-of-houston",
    name: "University of Houston",
    location: "Houston, TX",
    state: "TX",
    acceptance_rate: 66.0,
    avg_cost_instate: 12136,
    avg_cost_outstate: 26696,
    graduation_rate: 59,
    total_enrollment: 47090,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uh.edu",
    programs: [
      "Engineering",
      "Business",
      "Hotel Management",
      "Optometry",
      "Biology",
      "Computer Science",
      "Psychology",
      "Pharmacy",
    ],
  },
  {
    slug: "texas-am-university",
    name: "Texas A&M University",
    location: "College Station, TX",
    state: "TX",
    acceptance_rate: 57.0,
    avg_cost_instate: 13239,
    avg_cost_outstate: 40139,
    graduation_rate: 83,
    total_enrollment: 74829,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.tamu.edu",
    programs: [
      "Engineering",
      "Agriculture",
      "Business",
      "Veterinary Medicine",
      "Biology",
      "Computer Science",
      "Architecture",
      "Biomedical Science",
    ],
  },
  {
    slug: "baylor-university",
    name: "Baylor University",
    location: "Waco, TX",
    state: "TX",
    acceptance_rate: 47.0,
    avg_cost_instate: 53688,
    avg_cost_outstate: 53688,
    graduation_rate: 80,
    total_enrollment: 20626,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.baylor.edu",
    programs: [
      "Business",
      "Nursing",
      "Biology",
      "Engineering",
      "Communications",
      "Pre-Medicine",
      "Education",
      "Psychology",
    ],
  },
  {
    slug: "texas-christian-university",
    name: "Texas Christian University",
    location: "Fort Worth, TX",
    state: "TX",
    acceptance_rate: 38.0,
    avg_cost_instate: 55620,
    avg_cost_outstate: 55620,
    graduation_rate: 81,
    total_enrollment: 12281,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.tcu.edu",
    programs: [
      "Business",
      "Nursing",
      "Communication",
      "Biology",
      "Psychology",
      "Education",
      "Engineering",
      "Fine Arts",
    ],
  },
  {
    slug: "southern-methodist-university",
    name: "Southern Methodist University",
    location: "Dallas, TX",
    state: "TX",
    acceptance_rate: 49.0,
    avg_cost_instate: 61526,
    avg_cost_outstate: 61526,
    graduation_rate: 82,
    total_enrollment: 12096,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.smu.edu",
    programs: [
      "Business",
      "Engineering",
      "Economics",
      "Computer Science",
      "Political Science",
      "Art",
      "Communications",
      "Data Science",
    ],
  },
  {
    slug: "rice-university",
    name: "Rice University",
    location: "Houston, TX",
    state: "TX",
    acceptance_rate: 7.7,
    avg_cost_instate: 57210,
    avg_cost_outstate: 57210,
    graduation_rate: 94,
    total_enrollment: 8285,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.rice.edu",
    programs: [
      "Engineering",
      "Computer Science",
      "Economics",
      "Biology",
      "Architecture",
      "Music",
      "Business",
      "Physics",
    ],
  },

  // ── Expanded: Gulf South ───────────────────────────────────
  {
    slug: "tulane-university",
    name: "Tulane University",
    location: "New Orleans, LA",
    state: "LA",
    acceptance_rate: 11.0,
    avg_cost_instate: 62844,
    avg_cost_outstate: 62844,
    graduation_rate: 86,
    total_enrollment: 14046,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://tulane.edu",
    programs: [
      "Business",
      "Public Health",
      "Biology",
      "Architecture",
      "Political Science",
      "Psychology",
      "Computer Science",
      "Latin American Studies",
    ],
  },

  // ── Expanded: Northeast Private ────────────────────────────
  {
    slug: "fordham-university",
    name: "Fordham University",
    location: "Bronx, NY",
    state: "NY",
    acceptance_rate: 46.0,
    avg_cost_instate: 61476,
    avg_cost_outstate: 61476,
    graduation_rate: 83,
    total_enrollment: 16938,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.fordham.edu",
    programs: [
      "Business",
      "Communications",
      "Biology",
      "Political Science",
      "Psychology",
      "Social Work",
      "Economics",
      "Finance",
    ],
  },
  {
    slug: "boston-college",
    name: "Boston College",
    location: "Chestnut Hill, MA",
    state: "MA",
    acceptance_rate: 17.0,
    avg_cost_instate: 65424,
    avg_cost_outstate: 65424,
    graduation_rate: 94,
    total_enrollment: 14932,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.bc.edu",
    programs: [
      "Business",
      "Economics",
      "Biology",
      "Nursing",
      "Political Science",
      "Computer Science",
      "Psychology",
      "Communication",
    ],
  },
  {
    slug: "northeastern-university",
    name: "Northeastern University",
    location: "Boston, MA",
    state: "MA",
    acceptance_rate: 7.0,
    avg_cost_instate: 60192,
    avg_cost_outstate: 60192,
    graduation_rate: 91,
    total_enrollment: 23496,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.northeastern.edu",
    programs: [
      "Engineering",
      "Business",
      "Computer Science",
      "Health Sciences",
      "Biology",
      "Cybersecurity",
      "Political Science",
      "Communications",
    ],
  },
  {
    slug: "tufts-university",
    name: "Tufts University",
    location: "Medford, MA",
    state: "MA",
    acceptance_rate: 9.5,
    avg_cost_instate: 65222,
    avg_cost_outstate: 65222,
    graduation_rate: 94,
    total_enrollment: 12955,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.tufts.edu",
    programs: [
      "International Relations",
      "Biology",
      "Computer Science",
      "Economics",
      "Engineering",
      "Political Science",
      "Psychology",
      "Child Development",
    ],
  },
  {
    slug: "brandeis-university",
    name: "Brandeis University",
    location: "Waltham, MA",
    state: "MA",
    acceptance_rate: 31.0,
    avg_cost_instate: 62874,
    avg_cost_outstate: 62874,
    graduation_rate: 90,
    total_enrollment: 5854,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.brandeis.edu",
    programs: [
      "Biology",
      "Economics",
      "Psychology",
      "Business",
      "Computer Science",
      "Neuroscience",
      "Politics",
      "Health Policy",
    ],
  },

  // ── Expanded: New England Public ───────────────────────────
  {
    slug: "university-of-connecticut",
    name: "University of Connecticut",
    location: "Storrs, CT",
    state: "CT",
    acceptance_rate: 56.0,
    avg_cost_instate: 17226,
    avg_cost_outstate: 42162,
    graduation_rate: 85,
    total_enrollment: 32257,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://uconn.edu",
    programs: [
      "Business",
      "Engineering",
      "Nursing",
      "Biology",
      "Psychology",
      "Education",
      "Pharmacy",
      "Communication",
    ],
  },
  {
    slug: "university-of-rhode-island",
    name: "University of Rhode Island",
    location: "Kingston, RI",
    state: "RI",
    acceptance_rate: 76.0,
    avg_cost_instate: 15478,
    avg_cost_outstate: 33636,
    graduation_rate: 69,
    total_enrollment: 17092,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uri.edu",
    programs: [
      "Pharmacy",
      "Nursing",
      "Engineering",
      "Marine Biology",
      "Business",
      "Psychology",
      "Kinesiology",
      "Education",
    ],
  },
  {
    slug: "brown-university",
    name: "Brown University",
    location: "Providence, RI",
    state: "RI",
    acceptance_rate: 5.0,
    avg_cost_instate: 66274,
    avg_cost_outstate: 66274,
    graduation_rate: 96,
    total_enrollment: 10696,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.brown.edu",
    programs: [
      "Computer Science",
      "Economics",
      "Biology",
      "Applied Mathematics",
      "Political Science",
      "Engineering",
      "Neuroscience",
      "History",
    ],
  },
  {
    slug: "dartmouth-college",
    name: "Dartmouth College",
    location: "Hanover, NH",
    state: "NH",
    acceptance_rate: 6.2,
    avg_cost_instate: 65202,
    avg_cost_outstate: 65202,
    graduation_rate: 96,
    total_enrollment: 6834,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://home.dartmouth.edu",
    programs: [
      "Economics",
      "Government",
      "Computer Science",
      "Engineering",
      "Biology",
      "History",
      "Mathematics",
      "Psychology",
    ],
  },
  {
    slug: "university-of-new-hampshire",
    name: "University of New Hampshire",
    location: "Durham, NH",
    state: "NH",
    acceptance_rate: 80.0,
    avg_cost_instate: 19842,
    avg_cost_outstate: 37690,
    graduation_rate: 76,
    total_enrollment: 15482,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.unh.edu",
    programs: [
      "Business",
      "Engineering",
      "Biology",
      "Nursing",
      "Environmental Science",
      "Hospitality",
      "Psychology",
      "Education",
    ],
  },
  {
    slug: "university-of-vermont",
    name: "University of Vermont",
    location: "Burlington, VT",
    state: "VT",
    acceptance_rate: 62.0,
    avg_cost_instate: 19304,
    avg_cost_outstate: 45582,
    graduation_rate: 78,
    total_enrollment: 13734,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.uvm.edu",
    programs: [
      "Environmental Science",
      "Business",
      "Biology",
      "Nursing",
      "Engineering",
      "Education",
      "Psychology",
      "Food Science",
    ],
  },

  // ── Expanded: New York ─────────────────────────────────────
  {
    slug: "syracuse-university",
    name: "Syracuse University",
    location: "Syracuse, NY",
    state: "NY",
    acceptance_rate: 54.0,
    avg_cost_instate: 60014,
    avg_cost_outstate: 60014,
    graduation_rate: 82,
    total_enrollment: 22850,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.syracuse.edu",
    programs: [
      "Communications",
      "Business",
      "Architecture",
      "Engineering",
      "Information Studies",
      "Education",
      "Public Affairs",
      "Sport Management",
    ],
  },
  {
    slug: "university-of-rochester",
    name: "University of Rochester",
    location: "Rochester, NY",
    state: "NY",
    acceptance_rate: 35.0,
    avg_cost_instate: 63210,
    avg_cost_outstate: 63210,
    graduation_rate: 88,
    total_enrollment: 12174,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.rochester.edu",
    programs: [
      "Music",
      "Optics",
      "Engineering",
      "Biology",
      "Economics",
      "Computer Science",
      "Nursing",
      "Political Science",
    ],
  },
  {
    slug: "suny-buffalo",
    name: "SUNY Buffalo",
    location: "Buffalo, NY",
    state: "NY",
    acceptance_rate: 72.0,
    avg_cost_instate: 10546,
    avg_cost_outstate: 27546,
    graduation_rate: 75,
    total_enrollment: 32347,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.buffalo.edu",
    programs: [
      "Engineering",
      "Business",
      "Pharmacy",
      "Nursing",
      "Computer Science",
      "Biology",
      "Architecture",
      "Psychology",
    ],
  },
  {
    slug: "suny-stony-brook",
    name: "SUNY Stony Brook",
    location: "Stony Brook, NY",
    state: "NY",
    acceptance_rate: 49.0,
    avg_cost_instate: 10556,
    avg_cost_outstate: 27556,
    graduation_rate: 76,
    total_enrollment: 27368,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.stonybrook.edu",
    programs: [
      "Computer Science",
      "Engineering",
      "Biology",
      "Health Sciences",
      "Business",
      "Psychology",
      "Nursing",
      "Marine Science",
    ],
  },

  // ── Expanded: New Jersey ───────────────────────────────────
  {
    slug: "rutgers-university",
    name: "Rutgers University",
    location: "New Brunswick, NJ",
    state: "NJ",
    acceptance_rate: 66.0,
    avg_cost_instate: 16592,
    avg_cost_outstate: 35636,
    graduation_rate: 82,
    total_enrollment: 50411,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.rutgers.edu",
    programs: [
      "Business",
      "Engineering",
      "Pharmacy",
      "Biology",
      "Computer Science",
      "Nursing",
      "Communication",
      "Public Health",
    ],
  },
  {
    slug: "seton-hall-university",
    name: "Seton Hall University",
    location: "South Orange, NJ",
    state: "NJ",
    acceptance_rate: 77.0,
    avg_cost_instate: 48940,
    avg_cost_outstate: 48940,
    graduation_rate: 71,
    total_enrollment: 9783,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.shu.edu",
    programs: [
      "Nursing",
      "Business",
      "Biology",
      "Diplomacy",
      "Education",
      "Communication",
      "Criminal Justice",
      "Psychology",
    ],
  },

  // ── Expanded: Massachusetts ────────────────────────────────
  {
    slug: "university-of-massachusetts-amherst",
    name: "University of Massachusetts Amherst",
    location: "Amherst, MA",
    state: "MA",
    acceptance_rate: 64.0,
    avg_cost_instate: 16952,
    avg_cost_outstate: 38712,
    graduation_rate: 81,
    total_enrollment: 32208,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.umass.edu",
    programs: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Nursing",
      "Hospitality",
      "Psychology",
      "Public Health",
    ],
  },
  {
    slug: "worcester-polytechnic-institute",
    name: "Worcester Polytechnic Institute",
    location: "Worcester, MA",
    state: "MA",
    acceptance_rate: 49.0,
    avg_cost_instate: 58322,
    avg_cost_outstate: 58322,
    graduation_rate: 88,
    total_enrollment: 7314,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.wpi.edu",
    programs: [
      "Engineering",
      "Computer Science",
      "Robotics",
      "Biology",
      "Business",
      "Data Science",
      "Biomedical Engineering",
      "Physics",
    ],
  },

  // ── Expanded: Georgia & Southeast ──────────────────────────
  {
    slug: "emory-university",
    name: "Emory University",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 11.0,
    avg_cost_instate: 60774,
    avg_cost_outstate: 60774,
    graduation_rate: 93,
    total_enrollment: 15451,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.emory.edu",
    programs: [
      "Business",
      "Biology",
      "Nursing",
      "Economics",
      "Psychology",
      "Political Science",
      "Computer Science",
      "Public Health",
    ],
  },
  {
    slug: "georgia-state-university",
    name: "Georgia State University",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 67.0,
    avg_cost_instate: 11076,
    avg_cost_outstate: 30114,
    graduation_rate: 56,
    total_enrollment: 54016,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.gsu.edu",
    programs: [
      "Business",
      "Biology",
      "Criminal Justice",
      "Nursing",
      "Psychology",
      "Computer Science",
      "Film & Media",
      "Public Health",
    ],
  },

  // ── Expanded: Mississippi ──────────────────────────────────
  {
    slug: "university-of-mississippi",
    name: "University of Mississippi",
    location: "Oxford, MS",
    state: "MS",
    acceptance_rate: 87.0,
    avg_cost_instate: 9562,
    avg_cost_outstate: 26380,
    graduation_rate: 64,
    total_enrollment: 22456,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://olemiss.edu",
    programs: [
      "Pharmacy",
      "Accountancy",
      "Business",
      "Biology",
      "Criminal Justice",
      "Education",
      "Engineering",
      "Journalism",
    ],
  },
  {
    slug: "mississippi-state-university",
    name: "Mississippi State University",
    location: "Starkville, MS",
    state: "MS",
    acceptance_rate: 81.0,
    avg_cost_instate: 9738,
    avg_cost_outstate: 25188,
    graduation_rate: 63,
    total_enrollment: 22649,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.msstate.edu",
    programs: [
      "Engineering",
      "Agriculture",
      "Business",
      "Veterinary Medicine",
      "Architecture",
      "Education",
      "Biology",
      "Computer Science",
    ],
  },

  // ── Expanded: Florida ──────────────────────────────────────
  {
    slug: "university-of-south-florida",
    name: "University of South Florida",
    location: "Tampa, FL",
    state: "FL",
    acceptance_rate: 42.0,
    avg_cost_instate: 6410,
    avg_cost_outstate: 17324,
    graduation_rate: 74,
    total_enrollment: 50577,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.usf.edu",
    programs: [
      "Business",
      "Engineering",
      "Nursing",
      "Biology",
      "Biomedical Science",
      "Public Health",
      "Psychology",
      "Education",
    ],
  },
  {
    slug: "florida-international-university",
    name: "Florida International University",
    location: "Miami, FL",
    state: "FL",
    acceptance_rate: 58.0,
    avg_cost_instate: 6558,
    avg_cost_outstate: 18954,
    graduation_rate: 63,
    total_enrollment: 58711,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.fiu.edu",
    programs: [
      "Business",
      "Engineering",
      "Hospitality Management",
      "International Relations",
      "Biology",
      "Nursing",
      "Computer Science",
      "Criminal Justice",
    ],
  },
  {
    slug: "university-of-central-florida",
    name: "University of Central Florida",
    location: "Orlando, FL",
    state: "FL",
    acceptance_rate: 41.0,
    avg_cost_instate: 6368,
    avg_cost_outstate: 22467,
    graduation_rate: 75,
    total_enrollment: 71948,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.ucf.edu",
    programs: [
      "Engineering",
      "Business",
      "Hospitality Management",
      "Computer Science",
      "Nursing",
      "Biology",
      "Education",
      "Optics",
    ],
  },

  // ── Expanded: Hawaii ───────────────────────────────────────
  {
    slug: "university-of-hawaii",
    name: "University of Hawaii",
    location: "Honolulu, HI",
    state: "HI",
    acceptance_rate: 83.0,
    avg_cost_instate: 12186,
    avg_cost_outstate: 35862,
    graduation_rate: 62,
    total_enrollment: 18865,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://manoa.hawaii.edu",
    programs: [
      "Marine Biology",
      "Hawaiian Studies",
      "Business",
      "Engineering",
      "Biology",
      "Tourism",
      "Astronomy",
      "Nursing",
    ],
  },

  // ── Expanded: HBCUs ────────────────────────────────────────
  {
    slug: "hampton-university",
    name: "Hampton University",
    location: "Hampton, VA",
    state: "VA",
    acceptance_rate: 36.0,
    avg_cost_instate: 29560,
    avg_cost_outstate: 29560,
    graduation_rate: 55,
    total_enrollment: 3624,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://home.hamptonu.edu",
    programs: [
      "Nursing",
      "Biology",
      "Business",
      "Journalism",
      "Architecture",
      "Marine Science",
      "Psychology",
      "Engineering",
    ],
  },
  {
    slug: "xavier-university-of-louisiana",
    name: "Xavier University of Louisiana",
    location: "New Orleans, LA",
    state: "LA",
    acceptance_rate: 56.0,
    avg_cost_instate: 27224,
    avg_cost_outstate: 27224,
    graduation_rate: 45,
    total_enrollment: 3364,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.xula.edu",
    programs: [
      "Biology",
      "Pharmacy",
      "Chemistry",
      "Pre-Medicine",
      "Psychology",
      "Business",
      "Education",
      "Public Health",
    ],
  },
  {
    slug: "grambling-state-university",
    name: "Grambling State University",
    location: "Grambling, LA",
    state: "LA",
    acceptance_rate: 44.0,
    avg_cost_instate: 9422,
    avg_cost_outstate: 17792,
    graduation_rate: 35,
    total_enrollment: 5300,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.gram.edu",
    programs: [
      "Nursing",
      "Criminal Justice",
      "Business",
      "Biology",
      "Computer Science",
      "Mass Communication",
      "Education",
      "Sport Management",
    ],
  },
  {
    slug: "prairie-view-am",
    name: "Prairie View A&M",
    location: "Prairie View, TX",
    state: "TX",
    acceptance_rate: 60.0,
    avg_cost_instate: 11760,
    avg_cost_outstate: 23860,
    graduation_rate: 37,
    total_enrollment: 8732,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.pvamu.edu",
    programs: [
      "Nursing",
      "Engineering",
      "Business",
      "Biology",
      "Criminal Justice",
      "Architecture",
      "Computer Science",
      "Education",
    ],
  },
  {
    slug: "florida-am-university",
    name: "Florida A&M University",
    location: "Tallahassee, FL",
    state: "FL",
    acceptance_rate: 38.0,
    avg_cost_instate: 5785,
    avg_cost_outstate: 17725,
    graduation_rate: 44,
    total_enrollment: 10031,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.famu.edu",
    programs: [
      "Business",
      "Biology",
      "Criminal Justice",
      "Engineering",
      "Journalism",
      "Pharmacy",
      "Architecture",
      "Health Sciences",
    ],
  },
  {
    slug: "morgan-state-university",
    name: "Morgan State University",
    location: "Baltimore, MD",
    state: "MD",
    acceptance_rate: 64.0,
    avg_cost_instate: 9292,
    avg_cost_outstate: 19760,
    graduation_rate: 39,
    total_enrollment: 8872,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    official_url: "https://www.morgan.edu",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Nursing",
      "Architecture",
      "Social Work",
      "Computer Science",
      "Communications",
    ],
  },
];
