import { College } from "./types";

type CollegeSeed = Omit<College, "last_updated">;

export const COLLEGES_SEED: CollegeSeed[] = [
  // ── Ivy League ──────────────────────────────────────────────
  {
    slug: "harvard-university",
    name: "Harvard University",
    location: "Cambridge, MA",
    state: "MA",
    acceptance_rate: 3.2,
    avg_cost_instate: 57261,
    avg_cost_outstate: 57261,
    graduation_rate: 98,
    total_enrollment: 31345,
    photo_url:
      "https://images.unsplash.com/photo-1559135197-8a45ea74d367?w=1920&q=80",
    programs: [
      "Economics",
      "Computer Science",
      "Political Science",
      "Biology",
      "Mathematics",
      "History",
      "English",
      "Psychology",
    ],
  },
  {
    slug: "yale-university",
    name: "Yale University",
    location: "New Haven, CT",
    state: "CT",
    acceptance_rate: 4.4,
    avg_cost_instate: 62250,
    avg_cost_outstate: 62250,
    graduation_rate: 97,
    total_enrollment: 14776,
    photo_url:
      "https://images.unsplash.com/photo-1570992870781-e0e04a3e3de3?w=1920&q=80",
    programs: [
      "Economics",
      "Political Science",
      "History",
      "Molecular Biology",
      "Computer Science",
      "Psychology",
      "English",
      "Art",
    ],
  },
  {
    slug: "princeton-university",
    name: "Princeton University",
    location: "Princeton, NJ",
    state: "NJ",
    acceptance_rate: 3.7,
    avg_cost_instate: 59710,
    avg_cost_outstate: 59710,
    graduation_rate: 97,
    total_enrollment: 8623,
    photo_url:
      "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=1920&q=80",
    programs: [
      "Computer Science",
      "Economics",
      "Public Policy",
      "Engineering",
      "Mathematics",
      "Physics",
      "History",
      "Philosophy",
    ],
  },
  {
    slug: "columbia-university",
    name: "Columbia University",
    location: "New York, NY",
    state: "NY",
    acceptance_rate: 3.9,
    avg_cost_instate: 65524,
    avg_cost_outstate: 65524,
    graduation_rate: 95,
    total_enrollment: 36649,
    photo_url:
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1920&q=80",
    programs: [
      "Computer Science",
      "Economics",
      "Political Science",
      "Engineering",
      "English",
      "History",
      "Neuroscience",
      "Film Studies",
    ],
  },

  // ── Top Public Universities ─────────────────────────────────
  {
    slug: "uc-berkeley",
    name: "University of California, Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    acceptance_rate: 11.6,
    avg_cost_instate: 15602,
    avg_cost_outstate: 46326,
    graduation_rate: 93,
    total_enrollment: 45307,
    photo_url:
      "https://images.unsplash.com/photo-1597926661974-69a3c585e032?w=1920&q=80",
    programs: [
      "Computer Science",
      "Electrical Engineering",
      "Business",
      "Biology",
      "Economics",
      "Data Science",
      "Environmental Science",
      "Chemistry",
    ],
  },
  {
    slug: "ucla",
    name: "University of California, Los Angeles",
    location: "Los Angeles, CA",
    state: "CA",
    acceptance_rate: 8.6,
    avg_cost_instate: 14312,
    avg_cost_outstate: 44830,
    graduation_rate: 92,
    total_enrollment: 47310,
    photo_url:
      "https://images.unsplash.com/photo-1580982324076-d95230f6e2f2?w=1920&q=80",
    programs: [
      "Biology",
      "Psychology",
      "Political Science",
      "Economics",
      "Film & Television",
      "Nursing",
      "Computer Science",
      "Communications",
    ],
  },
  {
    slug: "university-of-michigan",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    state: "MI",
    acceptance_rate: 17.7,
    avg_cost_instate: 17786,
    avg_cost_outstate: 57762,
    graduation_rate: 93,
    total_enrollment: 48090,
    photo_url:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1920&q=80",
    programs: [
      "Engineering",
      "Business",
      "Computer Science",
      "Economics",
      "Psychology",
      "Nursing",
      "Public Policy",
      "Kinesiology",
    ],
  },
  {
    slug: "university-of-virginia",
    name: "University of Virginia",
    location: "Charlottesville, VA",
    state: "VA",
    acceptance_rate: 16.3,
    avg_cost_instate: 21426,
    avg_cost_outstate: 57222,
    graduation_rate: 94,
    total_enrollment: 26082,
    photo_url:
      "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1920&q=80",
    programs: [
      "Commerce",
      "Economics",
      "Biology",
      "Computer Science",
      "Engineering",
      "History",
      "Government",
      "Nursing",
    ],
  },
  {
    slug: "unc-chapel-hill",
    name: "University of North Carolina at Chapel Hill",
    location: "Chapel Hill, NC",
    state: "NC",
    acceptance_rate: 16.8,
    avg_cost_instate: 9021,
    avg_cost_outstate: 38562,
    graduation_rate: 91,
    total_enrollment: 32575,
    photo_url:
      "https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=1920&q=80",
    programs: [
      "Biology",
      "Business",
      "Computer Science",
      "Nursing",
      "Media & Journalism",
      "Political Science",
      "Psychology",
      "Public Health",
    ],
  },
  {
    slug: "ut-austin",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    state: "TX",
    acceptance_rate: 31.8,
    avg_cost_instate: 11448,
    avg_cost_outstate: 41070,
    graduation_rate: 88,
    total_enrollment: 53082,
    photo_url:
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=1920&q=80",
    programs: [
      "Business",
      "Engineering",
      "Computer Science",
      "Communications",
      "Biology",
      "Economics",
      "Nursing",
      "Architecture",
    ],
  },
  {
    slug: "georgia-tech",
    name: "Georgia Institute of Technology",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 16.0,
    avg_cost_instate: 12682,
    avg_cost_outstate: 37600,
    graduation_rate: 92,
    total_enrollment: 47000,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=80",
    programs: [
      "Computer Science",
      "Mechanical Engineering",
      "Industrial Engineering",
      "Biomedical Engineering",
      "Electrical Engineering",
      "Business",
      "Architecture",
      "Physics",
    ],
  },

  // ── Large State Universities ────────────────────────────────
  {
    slug: "ohio-state-university",
    name: "Ohio State University",
    location: "Columbus, OH",
    state: "OH",
    acceptance_rate: 53.0,
    avg_cost_instate: 12485,
    avg_cost_outstate: 36722,
    graduation_rate: 83,
    total_enrollment: 61369,
    photo_url:
      "https://images.unsplash.com/photo-1543505298-b8be9b0e5e4d?w=1920&q=80",
    programs: [
      "Business",
      "Engineering",
      "Biology",
      "Psychology",
      "Nursing",
      "Communication",
      "Computer Science",
      "Agriculture",
    ],
  },
  {
    slug: "penn-state",
    name: "Pennsylvania State University",
    location: "University Park, PA",
    state: "PA",
    acceptance_rate: 55.0,
    avg_cost_instate: 19286,
    avg_cost_outstate: 38824,
    graduation_rate: 86,
    total_enrollment: 88502,
    photo_url:
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=1920&q=80",
    programs: [
      "Engineering",
      "Business",
      "Agriculture",
      "Biology",
      "Kinesiology",
      "Computer Science",
      "Communications",
      "Education",
    ],
  },
  {
    slug: "university-of-florida",
    name: "University of Florida",
    location: "Gainesville, FL",
    state: "FL",
    acceptance_rate: 23.0,
    avg_cost_instate: 6381,
    avg_cost_outstate: 28658,
    graduation_rate: 90,
    total_enrollment: 55211,
    photo_url:
      "https://images.unsplash.com/photo-1535957998253-26ae1ef29506?w=1920&q=80",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Computer Science",
      "Journalism",
      "Agriculture",
      "Health Science",
      "Psychology",
    ],
  },
  {
    slug: "arizona-state-university",
    name: "Arizona State University",
    location: "Tempe, AZ",
    state: "AZ",
    acceptance_rate: 88.0,
    avg_cost_instate: 12447,
    avg_cost_outstate: 31200,
    graduation_rate: 69,
    total_enrollment: 78254,
    photo_url:
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1920&q=80",
    programs: [
      "Business",
      "Engineering",
      "Sustainability",
      "Computer Science",
      "Journalism",
      "Education",
      "Criminal Justice",
      "Nursing",
    ],
  },
  {
    slug: "florida-state-university",
    name: "Florida State University",
    location: "Tallahassee, FL",
    state: "FL",
    acceptance_rate: 25.0,
    avg_cost_instate: 6517,
    avg_cost_outstate: 21683,
    graduation_rate: 83,
    total_enrollment: 44862,
    photo_url:
      "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=1920&q=80",
    programs: [
      "Business",
      "Criminology",
      "Biology",
      "Psychology",
      "Film",
      "Music",
      "Engineering",
      "Education",
    ],
  },

  // ── Mid-Range Universities ──────────────────────────────────
  {
    slug: "james-madison-university",
    name: "James Madison University",
    location: "Harrisonburg, VA",
    state: "VA",
    acceptance_rate: 72.0,
    avg_cost_instate: 12488,
    avg_cost_outstate: 29602,
    graduation_rate: 82,
    total_enrollment: 22825,
    photo_url:
      "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=1920&q=80",
    programs: [
      "Health Sciences",
      "Business",
      "Biology",
      "Communication",
      "Nursing",
      "Kinesiology",
      "Education",
      "Computer Science",
    ],
  },
  {
    slug: "clemson-university",
    name: "Clemson University",
    location: "Clemson, SC",
    state: "SC",
    acceptance_rate: 43.0,
    avg_cost_instate: 16178,
    avg_cost_outstate: 40794,
    graduation_rate: 84,
    total_enrollment: 28466,
    photo_url:
      "https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=1920&q=80",
    programs: [
      "Engineering",
      "Business",
      "Biology",
      "Nursing",
      "Agriculture",
      "Architecture",
      "Computer Science",
      "Parks & Recreation",
    ],
  },
  {
    slug: "boise-state-university",
    name: "Boise State University",
    location: "Boise, ID",
    state: "ID",
    acceptance_rate: 83.0,
    avg_cost_instate: 8832,
    avg_cost_outstate: 25706,
    graduation_rate: 52,
    total_enrollment: 26067,
    photo_url:
      "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1920&q=80",
    programs: [
      "Business",
      "Health Science",
      "Engineering",
      "Nursing",
      "Education",
      "Criminal Justice",
      "Computer Science",
      "Kinesiology",
    ],
  },
  {
    slug: "iowa-state-university",
    name: "Iowa State University",
    location: "Ames, IA",
    state: "IA",
    acceptance_rate: 91.0,
    avg_cost_instate: 10264,
    avg_cost_outstate: 25976,
    graduation_rate: 76,
    total_enrollment: 30708,
    photo_url:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1920&q=80",
    programs: [
      "Engineering",
      "Agriculture",
      "Business",
      "Biology",
      "Computer Science",
      "Veterinary Medicine",
      "Design",
      "Education",
    ],
  },

  // ── Liberal Arts Colleges ───────────────────────────────────
  {
    slug: "williams-college",
    name: "Williams College",
    location: "Williamstown, MA",
    state: "MA",
    acceptance_rate: 8.5,
    avg_cost_instate: 63450,
    avg_cost_outstate: 63450,
    graduation_rate: 96,
    total_enrollment: 2089,
    photo_url:
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1920&q=80",
    programs: [
      "Economics",
      "Mathematics",
      "English",
      "Psychology",
      "Art History",
      "Biology",
      "Political Science",
      "Philosophy",
    ],
  },
  {
    slug: "amherst-college",
    name: "Amherst College",
    location: "Amherst, MA",
    state: "MA",
    acceptance_rate: 7.3,
    avg_cost_instate: 65100,
    avg_cost_outstate: 65100,
    graduation_rate: 95,
    total_enrollment: 1971,
    photo_url:
      "https://images.unsplash.com/photo-1592495981488-073153776d9a?w=1920&q=80",
    programs: [
      "Economics",
      "Mathematics",
      "English",
      "Political Science",
      "Psychology",
      "Biology",
      "Computer Science",
      "Law & Jurisprudence",
    ],
  },
  {
    slug: "bowdoin-college",
    name: "Bowdoin College",
    location: "Brunswick, ME",
    state: "ME",
    acceptance_rate: 8.7,
    avg_cost_instate: 64120,
    avg_cost_outstate: 64120,
    graduation_rate: 95,
    total_enrollment: 1878,
    photo_url:
      "https://images.unsplash.com/photo-1580977276076-ae4b8c219b8e?w=1920&q=80",
    programs: [
      "Government",
      "Economics",
      "Mathematics",
      "Biology",
      "English",
      "Earth & Oceanographic Science",
      "Computer Science",
      "Neuroscience",
    ],
  },

  // ── HBCUs ──────────────────────────────────────────────────
  {
    slug: "howard-university",
    name: "Howard University",
    location: "Washington, DC",
    state: "DC",
    acceptance_rate: 30.0,
    avg_cost_instate: 32053,
    avg_cost_outstate: 32053,
    graduation_rate: 66,
    total_enrollment: 12753,
    photo_url:
      "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=1920&q=80",
    programs: [
      "Biology",
      "Nursing",
      "Business",
      "Communications",
      "Political Science",
      "Psychology",
      "Engineering",
      "African American Studies",
    ],
  },
  {
    slug: "spelman-college",
    name: "Spelman College",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 29.0,
    avg_cost_instate: 31962,
    avg_cost_outstate: 31962,
    graduation_rate: 77,
    total_enrollment: 2264,
    photo_url:
      "https://images.unsplash.com/photo-1607013407627-6848f64e5fa4?w=1920&q=80",
    programs: [
      "Biology",
      "Psychology",
      "Political Science",
      "English",
      "Computer Science",
      "Economics",
      "Sociology",
      "Health Sciences",
    ],
  },
  {
    slug: "morehouse-college",
    name: "Morehouse College",
    location: "Atlanta, GA",
    state: "GA",
    acceptance_rate: 39.0,
    avg_cost_instate: 30342,
    avg_cost_outstate: 30342,
    graduation_rate: 60,
    total_enrollment: 2256,
    photo_url:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1920&q=80",
    programs: [
      "Business Administration",
      "Biology",
      "Computer Science",
      "Political Science",
      "Psychology",
      "Cinema & Media Studies",
      "Engineering",
      "Kinesiology",
    ],
  },

  // ── Technical Institutions ──────────────────────────────────
  {
    slug: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    state: "MA",
    acceptance_rate: 3.5,
    avg_cost_instate: 61990,
    avg_cost_outstate: 61990,
    graduation_rate: 96,
    total_enrollment: 11858,
    photo_url:
      "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=1920&q=80",
    programs: [
      "Computer Science",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Mathematics",
      "Physics",
      "Biology",
      "Economics",
      "Architecture",
    ],
  },
  {
    slug: "caltech",
    name: "California Institute of Technology",
    location: "Pasadena, CA",
    state: "CA",
    acceptance_rate: 2.7,
    avg_cost_instate: 63471,
    avg_cost_outstate: 63471,
    graduation_rate: 94,
    total_enrollment: 2397,
    photo_url:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1920&q=80",
    programs: [
      "Physics",
      "Computer Science",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Astrophysics",
    ],
  },
  {
    slug: "rpi",
    name: "Rensselaer Polytechnic Institute",
    location: "Troy, NY",
    state: "NY",
    acceptance_rate: 57.0,
    avg_cost_instate: 60551,
    avg_cost_outstate: 60551,
    graduation_rate: 86,
    total_enrollment: 7762,
    photo_url:
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1920&q=80",
    programs: [
      "Computer Science",
      "Engineering",
      "Business",
      "Architecture",
      "Biomedical Engineering",
      "Information Technology",
      "Physics",
      "Game Design",
    ],
  },

  // ── Community Colleges ──────────────────────────────────────
  {
    slug: "santa-monica-college",
    name: "Santa Monica College",
    location: "Santa Monica, CA",
    state: "CA",
    acceptance_rate: 100,
    avg_cost_instate: 1524,
    avg_cost_outstate: 12108,
    graduation_rate: 29,
    total_enrollment: 28000,
    photo_url:
      "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1920&q=80",
    programs: [
      "Business",
      "Nursing",
      "Liberal Arts",
      "Computer Science",
      "Film Production",
      "Accounting",
      "Early Childhood Education",
      "Graphic Design",
    ],
  },
  {
    slug: "northern-virginia-community-college",
    name: "Northern Virginia Community College",
    location: "Annandale, VA",
    state: "VA",
    acceptance_rate: 100,
    avg_cost_instate: 6255,
    avg_cost_outstate: 12815,
    graduation_rate: 25,
    total_enrollment: 67000,
    photo_url:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1920&q=80",
    programs: [
      "Liberal Arts",
      "Business",
      "Information Technology",
      "Engineering",
      "Nursing",
      "Cybersecurity",
      "Education",
      "Health Sciences",
    ],
  },
  {
    slug: "austin-community-college",
    name: "Austin Community College",
    location: "Austin, TX",
    state: "TX",
    acceptance_rate: 100,
    avg_cost_instate: 2970,
    avg_cost_outstate: 10830,
    graduation_rate: 20,
    total_enrollment: 41000,
    photo_url:
      "https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=80",
    programs: [
      "Business",
      "Computer Science",
      "Nursing",
      "Welding",
      "Veterinary Technology",
      "Culinary Arts",
      "Liberal Arts",
      "Automotive Technology",
    ],
  },
];
