export interface MajorPage {
  slug: string;
  label: string;
  keywords: string[];
  howToChoose: string;
  careerPaths: string;
}

export const MAJOR_PAGES: MajorPage[] = [
  { slug: "computer-science", label: "Computer Science", keywords: ["Computer Science", "Software", "Computing", "Information Technology", "Coding"], howToChoose: "Look for programs with strong industry partnerships, internship pipelines, and faculty who are active researchers. Consider whether you prefer a theoretical CS program (more math-heavy) or an applied one (more project-based). Co-op programs that alternate semesters of study with paid work experience are especially valuable in CS.", careerPaths: "Software Engineer, Data Scientist, Product Manager, Cybersecurity Analyst, AI/ML Engineer" },
  { slug: "nursing", label: "Nursing", keywords: ["Nursing", "RN", "BSN", "Health Sciences"], howToChoose: "Accreditation matters most — look for CCNE or ACEN accredited programs. Check NCLEX pass rates (above 90% is strong). Consider whether you want a traditional BSN or an accelerated program. Clinical placement quality and hospital partnerships are crucial.", careerPaths: "Registered Nurse, Nurse Practitioner, Clinical Nurse Specialist, Nurse Anesthetist, Public Health Nurse" },
  { slug: "business", label: "Business & Management", keywords: ["Business", "Management", "Marketing", "Entrepreneurship", "MBA"], howToChoose: "AACSB accreditation is the gold standard. Look for programs with real-world consulting projects, strong alumni networks, and career placement rates. Consider whether you want a broad business degree or a specialization like finance, marketing, or entrepreneurship.", careerPaths: "Management Consultant, Marketing Manager, Financial Analyst, Entrepreneur, Operations Manager" },
  { slug: "engineering", label: "Engineering", keywords: ["Engineering", "Mechanical", "Civil", "Electrical", "Chemical", "Aerospace"], howToChoose: "ABET accreditation is essential for licensure. Research which engineering disciplines the school excels at — a school strong in mechanical may not be as strong in biomedical. Look for undergraduate research opportunities and industry capstone projects.", careerPaths: "Mechanical Engineer, Civil Engineer, Software Engineer, Biomedical Engineer, Aerospace Engineer" },
  { slug: "psychology", label: "Psychology", keywords: ["Psychology", "Behavioral Science", "Cognitive Science"], howToChoose: "If you plan to become a licensed psychologist, you'll need a doctoral degree — choose an undergraduate program with strong research opportunities and faculty mentorship. Look for programs with lab access and opportunities to co-author research papers.", careerPaths: "Clinical Psychologist, School Counselor, UX Researcher, Human Resources Specialist, Market Research Analyst" },
  { slug: "biology", label: "Biology & Pre-Med", keywords: ["Biology", "Pre-Med", "Biomedical", "Biochemistry", "Life Sciences"], howToChoose: "For pre-med students, look at medical school acceptance rates and MCAT prep support. Strong undergraduate research programs and access to teaching hospitals are major advantages. Consider schools with early assurance medical programs if you're certain about medicine.", careerPaths: "Physician, Research Scientist, Pharmacist, Genetic Counselor, Biotech Researcher" },
  { slug: "education", label: "Education", keywords: ["Education", "Teaching", "Early Childhood", "Special Education"], howToChoose: "State licensure requirements vary — choose a program accredited in the state where you want to teach. Look for programs with extensive student teaching placements and partnerships with local school districts. Consider specializations like special education or ESL.", careerPaths: "K-12 Teacher, School Administrator, Curriculum Developer, Education Policy Analyst, Instructional Designer" },
  { slug: "communications", label: "Communications & Media", keywords: ["Communications", "Media", "Journalism", "Public Relations", "Broadcasting"], howToChoose: "Look for programs with working newsrooms, radio stations, or production studios. Industry connections and internship programs matter more than rankings in communications. Consider whether you want to focus on journalism, PR, digital media, or broadcast.", careerPaths: "Public Relations Specialist, Social Media Manager, Journalist, Content Strategist, Communications Director" },
  { slug: "criminal-justice", label: "Criminal Justice", keywords: ["Criminal Justice", "Criminology", "Law Enforcement", "Forensic Science"], howToChoose: "Consider whether you want a theoretical criminology program or a more applied law enforcement track. Look for programs with partnerships with local police departments, courts, and federal agencies. Internship opportunities with the FBI, ATF, or state agencies are valuable.", careerPaths: "Police Officer, FBI Agent, Probation Officer, Crime Analyst, Corrections Administrator" },
  { slug: "social-work", label: "Social Work", keywords: ["Social Work", "Human Services", "Community Development"], howToChoose: "CSWE accreditation is essential for licensure. Look for programs with strong field placement programs — you'll spend hundreds of hours in supervised practice. Consider whether you want to focus on clinical social work, community organizing, or policy advocacy.", careerPaths: "Clinical Social Worker, Child Welfare Specialist, School Social Worker, Community Organizer, Policy Advocate" },
  { slug: "graphic-design", label: "Graphic Design", keywords: ["Graphic Design", "Visual Arts", "Digital Design", "UX Design", "UI Design"], howToChoose: "Portfolio quality matters more than school prestige in design. Look for programs that teach both traditional design principles and modern tools (Figma, Adobe Suite). Strong industry partnerships and senior capstone projects with real clients are key differentiators.", careerPaths: "Graphic Designer, UX/UI Designer, Art Director, Brand Designer, Motion Graphics Artist" },
  { slug: "finance", label: "Finance & Accounting", keywords: ["Finance", "Accounting", "Economics", "Banking", "CPA"], howToChoose: "For accounting, choose a program that prepares you for the CPA exam — check pass rates. For finance, look for schools with strong Wall Street or fintech placement. Bloomberg terminals, student-managed investment funds, and Big Four recruiting relationships are indicators of quality.", careerPaths: "Financial Analyst, Investment Banker, Accountant (CPA), Financial Planner, Risk Manager" },
  { slug: "political-science", label: "Political Science & Pre-Law", keywords: ["Political Science", "Government", "Pre-Law", "Public Policy", "International Affairs"], howToChoose: "For pre-law students, undergraduate major matters less than GPA and LSAT scores — but political science builds relevant analytical skills. Look for programs near state capitals or Washington DC for internship access. Moot court and Model UN programs are valuable extracurriculars.", careerPaths: "Lawyer, Legislative Aide, Policy Analyst, Campaign Manager, Diplomat" },
  { slug: "architecture", label: "Architecture", keywords: ["Architecture", "Urban Planning", "Interior Design", "Landscape Architecture"], howToChoose: "NAAB accreditation is required for licensure. Architecture programs are typically 5 years for a B.Arch or 4+2 for B.S. + M.Arch. Look for strong studio culture, study abroad programs, and faculty who are practicing architects.", careerPaths: "Architect, Urban Planner, Interior Designer, Landscape Architect, Sustainability Consultant" },
  { slug: "film", label: "Film & Theater Arts", keywords: ["Film", "Theater", "Acting", "Screenwriting", "Performing Arts", "Drama"], howToChoose: "In film and theater, connections matter as much as education. Look for programs in or near major production hubs (LA, NYC, Atlanta). Access to professional-grade equipment, industry guest lecturers, and festival submission support are important. Check alumni career outcomes.", careerPaths: "Film Director, Screenwriter, Actor, Producer, Cinematographer" },
  { slug: "environmental-science", label: "Environmental Science", keywords: ["Environmental Science", "Ecology", "Sustainability", "Conservation", "Climate"], howToChoose: "Look for programs with field research opportunities, GIS training, and partnerships with environmental agencies. Proximity to diverse ecosystems (coasts, forests, deserts) provides hands-on learning advantages. Consider whether you prefer a science-heavy or policy-focused track.", careerPaths: "Environmental Scientist, Conservation Biologist, Sustainability Manager, Climate Policy Analyst, Park Ranger" },
  { slug: "data-science", label: "Data Science & AI", keywords: ["Data Science", "Artificial Intelligence", "Machine Learning", "Statistics", "Analytics"], howToChoose: "Data science is interdisciplinary — look for programs that combine statistics, computer science, and domain expertise. Industry capstone projects, access to cloud computing resources, and partnerships with tech companies are strong indicators. Consider whether the program emphasises theory or applied skills.", careerPaths: "Data Scientist, Machine Learning Engineer, Business Intelligence Analyst, AI Researcher, Data Engineer" },
  { slug: "sports-management", label: "Sports Management & Kinesiology", keywords: ["Sports Management", "Kinesiology", "Exercise Science", "Athletic Training", "Recreation"], howToChoose: "Programs affiliated with Division I athletic departments offer unmatched practical experience. Look for internship pipelines to professional sports organizations, athletic brands, or sports media companies. Consider whether you want the business side (sports management) or the science side (kinesiology).", careerPaths: "Sports Agent, Athletic Director, Personal Trainer, Physical Therapist, Sports Marketing Manager" },
  { slug: "international-relations", label: "International Relations", keywords: ["International Relations", "International Studies", "Global Affairs", "Diplomacy"], howToChoose: "Language proficiency and study abroad are essential in IR. Look for programs with strong language departments, Model UN programs, and connections to think tanks or international organizations. Proximity to Washington DC, New York, or Geneva provides internship advantages.", careerPaths: "Diplomat, Intelligence Analyst, International Development Officer, Foreign Correspondent, NGO Manager" },
  { slug: "music", label: "Music & Performing Arts", keywords: ["Music", "Performing Arts", "Music Education", "Music Production", "Voice"], howToChoose: "Auditions are typically required. Consider the difference between conservatory programs (intensive performance focus) and university music departments (broader liberal arts context). Look for faculty who are active performers, quality practice facilities, and performance opportunities.", careerPaths: "Professional Musician, Music Teacher, Music Producer, Sound Engineer, Arts Administrator" },
];

export function getMajorBySlug(slug: string): MajorPage | undefined {
  return MAJOR_PAGES.find((m) => m.slug === slug);
}
