-- Migration 018: NPC URLs discovered via Google Custom Search
-- Generated by scripts/scrape-npc-urls-google.ts
-- Source: top Google result for "<college> net price calculator"
-- Only high-confidence results (.edu + NPC keyword in URL) are included.
-- Review scripts/npc_urls_results.csv for the full audit trail.

-- No high-confidence results.

SELECT count(*) AS with_npc_url FROM colleges WHERE npc_url IS NOT NULL;
